In [1]:
pip install apyori

Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5955 sha256=b7d067440af9461e7c6c785ca85c87dbb8c7321a74c14e7546b13a5df94adf2d
  Stored in directory: /Users/wiams/Library/Caches/pip/wheels/77/3d/a6/d317a6fb32be58a602b1e8c6b5d6f31f79322da554cad2a5ea
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2
Note: you may need to restart the kernel to use updated packages.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from apyori import apriori

In [5]:
census = pd.read_csv("census_catgr.csv")

In [3]:
census.head()

,Region,Residence Type,Family Composition,Population Base,Sex,Age,Marital Status,Student,Country of Birth,Health,Ethnic Group,Religion,Economic Activity,Occupation,Industry,Hours worked per week,No of hours,Approximated Social Grade,Indutry
0,North East,Not resident in a communal establishment,Married/same-sex civil partnership couple family,Usual resident,Female,55 to 64,Married or in a registered same-sex civil part...,No,UK,Good health,White,Christian,Economically inactive: Retired,"Process, Plant and Machine Operatives",2,"No code required - People aged under 16, peopl...",NaN,DE - Semi-skilled & unskilled manual occupatio...,Mining and quarrying; Manufacturing; Electrici...
1,North East,Not resident in a communal establishment,Cohabiting couple family,Usual resident,Female,0 to 15,Single - never married or never registered a s...,No,UK,Good health,White,No religion,No code required- Aged under 16 or students or...,"No code required - People aged under 16, peopl...",-9,"No code required - People aged under 16, peopl...",NaN,"No code required - People aged under 16, peopl...","No code required - People aged under 16, peopl..."
2,North East,Not resident in a communal establishment,Married/same-sex civil partnership couple family,Usual resident,Male,65 to 74,Married or in a registered same-sex civil part...,No,UK,Very good health,White,Christian,Economically inactive: Retired,"Process, Plant and Machine Operatives",2,"No code required - People aged under 16, peopl...",NaN,"C1 - Supervisory, clerical & junior managerial...",Mining and quarrying; Manufacturing; Electrici...
3,North East,Not resident in a communal establishment,Not in a family,Usual resident,Female,55 to 64,Divorced or formerly in a same-sex civil partn...,No,UK,Fair health,White,Christian,Economically inactive: Retired,Elementary Occupations,5,"No code required - People aged under 16, peopl...",NaN,DE - Semi-skilled & unskilled manual occupatio...,Accommodation and food service activities
4,North East,Not resident in a communal establishment,Married/same-sex civil partnership couple family,Usual resident,Male,0 to 15,Single - never married or never registered a s...,Yes,UK,Very good health,White,No religion,No code required- Aged under 16 or students or...,"No code required - People aged under 16, peopl...",-9,"No code required - People aged under 16, peopl...",NaN,"No code required - People aged under 16, peopl...","No code required - People aged under 16, peopl..."

In [6]:
census['No of hours']=census['No of hours'].fillna(0)

In [10]:
#transform numerical attributes into categorical ones
census['No of hours'] = pd.qcut(census['No of hours'], q=4, duplicates='drop')
census['No of hours'].value_counts(sort=False)

No of hours
(-0.001, 36.0]    431521
(36.0, 60.0]      138219
Name: count, dtype: int64

In [11]:
census.head()

,Region,Residence Type,Family Composition,Population Base,Sex,Age,Marital Status,Student,Country of Birth,Health,Ethnic Group,Religion,Economic Activity,Occupation,Industry,Hours worked per week,No of hours,Approximated Social Grade,Indutry
0,North East,Not resident in a communal establishment,Married/same-sex civil partnership couple family,Usual resident,Female,55 to 64,Married or in a registered same-sex civil part...,No,UK,Good health,White,Christian,Economically inactive: Retired,"Process, Plant and Machine Operatives",2,"No code required - People aged under 16, peopl...","(-0.001, 36.0]",DE - Semi-skilled & unskilled manual occupatio...,Mining and quarrying; Manufacturing; Electrici...
1,North East,Not resident in a communal establishment,Cohabiting couple family,Usual resident,Female,0 to 15,Single - never married or never registered a s...,No,UK,Good health,White,No religion,No code required- Aged under 16 or students or...,"No code required - People aged under 16, peopl...",-9,"No code required - People aged under 16, peopl...","(-0.001, 36.0]","No code required - People aged under 16, peopl...","No code required - People aged under 16, peopl..."
2,North East,Not resident in a communal establishment,Married/same-sex civil partnership couple family,Usual resident,Male,65 to 74,Married or in a registered same-sex civil part...,No,UK,Very good health,White,Christian,Economically inactive: Retired,"Process, Plant and Machine Operatives",2,"No code required - People aged under 16, peopl...","(-0.001, 36.0]","C1 - Supervisory, clerical & junior managerial...",Mining and quarrying; Manufacturing; Electrici...
3,North East,Not resident in a communal establishment,Not in a family,Usual resident,Female,55 to 64,Divorced or formerly in a same-sex civil partn...,No,UK,Fair health,White,Christian,Economically inactive: Retired,Elementary Occupations,5,"No code required - People aged under 16, peopl...","(-0.001, 36.0]",DE - Semi-skilled & unskilled manual occupatio...,Accommodation and food service activities
4,North East,Not resident in a communal establishment,Married/same-sex civil partnership couple family,Usual resident,Male,0 to 15,Single - never married or never registered a s...,Yes,UK,Very good health,White,No religion,No code required- Aged under 16 or students or...,"No code required - People aged under 16, peopl...",-9,"No code required - People aged under 16, peopl...","(-0.001, 36.0]","No code required - People aged under 16, peopl...","No code required - People aged under 16, peopl..."

In [12]:
census.shape

(569740, 19)

In [14]:
census1 = census.sample(frac=0.01, replace=False, random_state=1)
census1.shape

(5697, 19)

In [16]:
data_list = []
for row in range(0,5697):
    data_list.append([str(census1.values[row,column]) for column in range(0, 19)])
    
rules = apriori(data_list, min_support=0.25, min_confidence=0.25, min_length=2)
results = list(rules)

In [17]:
print(results)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [18]:
#Put the results into a dataframe to have the rules listed in a table
df = pd.DataFrame(columns=('Items','Antecedent','Consequent','Support','Confidence','Lift'))

Support =[]
Confidence = []
Lift = []
Items = []
Antecedent = []
Consequent=[]

for RelationRecord in results:
    for ordered_stat in RelationRecord.ordered_statistics:
        Support.append(RelationRecord.support)
        Items.append(RelationRecord.items)
        Antecedent.append(ordered_stat.items_base)
        Consequent.append(ordered_stat.items_add)
        Confidence.append(ordered_stat.confidence)
        Lift.append(ordered_stat.lift)

df['Items'] = list(map(set, Items))                                   
df['Antecedent'] = list(map(set, Antecedent))
df['Consequent'] = list(map(set, Consequent))
df['Support'] = Support
df['Confidence'] = Confidence
df['Lift']= Lift

#Sort resulted dataframe by Lift
df.sort_values(by ='Lift', ascending = False, inplace = True)

In [19]:
 df.reset_index(drop=True, inplace=True)

In [20]:
df.shape

(13307, 6)

In [21]:
df.head()

,Items,Antecedent,Consequent,Support,Confidence,Lift
0,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,0.975497,3.772848
1,"{No code required - People aged under 16, peop...",{-9},"{No code required - People aged under 16, peop...",0.265052,1.000000,3.772848
2,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.253116,1.000000,3.772848
3,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.253116,1.000000,3.772848
4,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,0.975497,3.772848

In [27]:
df.head(50)

,Items,Antecedent,Consequent,Support,Confidence,Lift
0,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,0.975497,3.772848
1,"{No code required - People aged under 16, peop...",{-9},"{No code required - People aged under 16, peop...",0.265052,1.000000,3.772848
2,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.253116,1.000000,3.772848
3,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.253116,1.000000,3.772848
4,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,0.975497,3.772848
5,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,0.975497,3.772848
6,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,0.975497,3.772848
7,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,0.975497,3.772848
8,"{No code required - People aged under 16, peop...",{-9},"{No code required - People aged under 16, peop...",0.258557,0.975497,3.772848
9,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.265052,1.000000,3.772848
10,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{Usual resident, No code required - People age...",0.253116,0.954967,3.772848
11,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.265052,1.000000,3.772848
12,"{No code required - People aged under 16, peop...","{(-0.001, 36.0], -9}","{No code required - People aged under 16, peop...",0.265052,1.000000,3.772848
13,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.265052,1.000000,3.772848
14,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.265052,1.000000,3.772848
15,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.265052,1.000000,3.772848
16,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.265052,1.000000,3.772848
17,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.265052,1.000000,3.772848
18,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,0.975497,3.772848
19,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.253116,1.000000,3.772848
20,"{No code required - People aged under 16, peop...","{Usual resident, No code required - People age...","{No code required - People aged under 16, peop...",0.253116,1.000000,3.772848
21,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{Usual resident, No code required - People age...",0.253116,0.954967,3.772848
22,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,0.975497,3.772848
23,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,0.975497,3.772848
24,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,0.975497,3.772848
25,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,0.975497,3.772848
26,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,0.975497,3.772848
27,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,1.000000,3.772848
28,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,1.000000,3.772848
29,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{-9, No code required - People aged under 16, ...",0.258557,0.975497,3.772848
30,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,1.000000,3.772848
31,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,1.000000,3.772848
32,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,0.975497,3.772848
33,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.253116,0.954967,3.772848
34,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.253116,0.954967,3.772848
35,"{No code required - People aged under 16, peop...","{Not resident in a communal establishment, -9}","{No code required - People aged under 16, peop...",0.258557,1.000000,3.772848
36,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.253116,0.954967,3.772848
37,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.265052,1.000000,3.772848
38,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{(-0.001, 36.0], No code required - People age...",0.265052,1.000000,3.772848
39,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.265052,1.000000,3.772848
40,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{(-0.001, 36.0], Not resident in a communal es...",0.258557,0.975497,3.772848
41,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,0.975497,3.772848
42,"{No code required - People aged under 16, peop...","{Not resident in a communal establishment, (-0...","{No code required - People aged under 16, peop...",0.258557,1.000000,3.772848
43,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{Not resident in a communal establishment, -9}",0.258557,0.975497,3.772848
44,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,1.000000,3.772848
45,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{(-0.001, 36.0], No code required - People age...",0.258557,1.000000,3.772848
46,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{(-0.001, 36.0], -9}",0.258557,1.000000,3.772848
47,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,1.000000,3.772848
48,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",{-9},0.258557,1.000000,3.772848
49,"{No code required - People aged under 16, peop...",{-9},"{No code required - People aged under 16, peop...",0.253116,0.954967,3.772848

In [30]:
above_1 = df[df["Lift"] > 1.5]

In [31]:
above_1.shape

(1270, 6)

In [32]:
above_1.head(50)

,Items,Antecedent,Consequent,Support,Confidence,Lift
0,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,0.975497,3.772848
1,"{No code required - People aged under 16, peop...",{-9},"{No code required - People aged under 16, peop...",0.265052,1.000000,3.772848
2,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.253116,1.000000,3.772848
3,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.253116,1.000000,3.772848
4,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,0.975497,3.772848
5,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,0.975497,3.772848
6,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,0.975497,3.772848
7,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,0.975497,3.772848
8,"{No code required - People aged under 16, peop...",{-9},"{No code required - People aged under 16, peop...",0.258557,0.975497,3.772848
9,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.265052,1.000000,3.772848
10,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{Usual resident, No code required - People age...",0.253116,0.954967,3.772848
11,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.265052,1.000000,3.772848
12,"{No code required - People aged under 16, peop...","{(-0.001, 36.0], -9}","{No code required - People aged under 16, peop...",0.265052,1.000000,3.772848
13,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.265052,1.000000,3.772848
14,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.265052,1.000000,3.772848
15,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.265052,1.000000,3.772848
16,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.265052,1.000000,3.772848
17,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.265052,1.000000,3.772848
18,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,0.975497,3.772848
19,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.253116,1.000000,3.772848
20,"{No code required - People aged under 16, peop...","{Usual resident, No code required - People age...","{No code required - People aged under 16, peop...",0.253116,1.000000,3.772848
21,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{Usual resident, No code required - People age...",0.253116,0.954967,3.772848
22,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,0.975497,3.772848
23,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,0.975497,3.772848
24,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,0.975497,3.772848
25,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,0.975497,3.772848
26,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,0.975497,3.772848
27,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,1.000000,3.772848
28,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,1.000000,3.772848
29,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{-9, No code required - People aged under 16, ...",0.258557,0.975497,3.772848
30,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,1.000000,3.772848
31,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,1.000000,3.772848
32,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,0.975497,3.772848
33,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.253116,0.954967,3.772848
34,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.253116,0.954967,3.772848
35,"{No code required - People aged under 16, peop...","{Not resident in a communal establishment, -9}","{No code required - People aged under 16, peop...",0.258557,1.000000,3.772848
36,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.253116,0.954967,3.772848
37,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.265052,1.000000,3.772848
38,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{(-0.001, 36.0], No code required - People age...",0.265052,1.000000,3.772848
39,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.265052,1.000000,3.772848
40,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{(-0.001, 36.0], Not resident in a communal es...",0.258557,0.975497,3.772848
41,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,0.975497,3.772848
42,"{No code required - People aged under 16, peop...","{Not resident in a communal establishment, (-0...","{No code required - People aged under 16, peop...",0.258557,1.000000,3.772848
43,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{Not resident in a communal establishment, -9}",0.258557,0.975497,3.772848
44,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,1.000000,3.772848
45,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{(-0.001, 36.0], No code required - People age...",0.258557,1.000000,3.772848
46,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{(-0.001, 36.0], -9}",0.258557,1.000000,3.772848
47,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",0.258557,1.000000,3.772848
48,"{No code required - People aged under 16, peop...","{No code required - People aged under 16, peop...",{-9},0.258557,1.000000,3.772848
49,"{No code required - People aged under 16, peop...",{-9},"{No code required - People aged under 16, peop...",0.253116,0.954967,3.772848

In [33]:
print(above_1.loc[[50]])

                                                Items  \
50  {No code required - People aged under 16, peop...

                                           Antecedent  \
50  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
50  {No code required - People aged under 16, peop...  0.253116    0.954967

        Lift
50  3.772848

In [34]:
for x in range(1270):
  print(above_1.loc[[x]])

                                               Items  \
0  {No code required - People aged under 16, peop...

                                          Antecedent  \
0  {No code required - People aged under 16, peop...

                                          Consequent   Support  Confidence  \
0  {No code required - People aged under 16, peop...  0.258557    0.975497

       Lift
0  3.772848
                                               Items Antecedent  \
1  {No code required - People aged under 16, peop...       {-9}

                                          Consequent   Support  Confidence  \
1  {No code required - People aged under 16, peop...  0.265052         1.0

       Lift
1  3.772848
                                               Items  \
2  {No code required - People aged under 16, peop...

                                          Antecedent  \
2  {No code required - People aged under 16, peop...

                                          Consequent   Support  Confidence  \
2  {No code required - People aged under 16, peop...  0.253116         1.0

       Lift
2  3.772848
                                               Items  \
3  {No code required - People aged under 16, peop...

                                          Antecedent  \
3  {No code required - People aged under 16, peop...

                                          Consequent   Support  Confidence  \
3  {No code required - People aged under 16, peop...  0.253116         1.0

       Lift
3  3.772848
                                               Items  \
4  {No code required - People aged under 16, peop...

                                          Antecedent  \
4  {No code required - People aged under 16, peop...

                                          Consequent   Support  Confidence  \
4  {No code required - People aged under 16, peop...  0.258557    0.975497

       Lift
4  3.772848
                                               Items  \
5  {No code required - People aged under 16, peop...

                                          Antecedent  \
5  {No code required - People aged under 16, peop...

                                          Consequent   Support  Confidence  \
5  {No code required - People aged under 16, peop...  0.258557    0.975497

       Lift
5  3.772848
                                               Items  \
6  {No code required - People aged under 16, peop...

                                          Antecedent  \
6  {No code required - People aged under 16, peop...

                                          Consequent   Support  Confidence  \
6  {No code required - People aged under 16, peop...  0.258557    0.975497

       Lift
6  3.772848
                                               Items  \
7  {No code required - People aged under 16, peop...

                                          Antecedent  \
7  {No code required - People aged under 16, peop...

                                          Consequent   Support  Confidence  \
7  {No code required - People aged under 16, peop...  0.258557    0.975497

       Lift
7  3.772848
                                               Items Antecedent  \
8  {No code required - People aged under 16, peop...       {-9}

                                          Consequent   Support  Confidence  \
8  {No code required - People aged under 16, peop...  0.258557    0.975497

       Lift
8  3.772848
                                               Items  \
9  {No code required - People aged under 16, peop...

                                          Antecedent  \
9  {No code required - People aged under 16, peop...

                                          Consequent   Support  Confidence  \
9  {No code required - People aged under 16, peop...  0.265052         1.0

       Lift
9  3.772848
                                                Items  \
10  {No code required - People aged under 16, peop...

                                           Antecedent  \
10  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
10  {Usual resident, No code required - People age...  0.253116    0.954967

        Lift
10  3.772848
                                                Items  \
11  {No code required - People aged under 16, peop...

                                           Antecedent  \
11  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
11  {No code required - People aged under 16, peop...  0.265052         1.0

        Lift
11  3.772848
                                                Items            Antecedent  \
12  {No code required - People aged under 16, peop...  {(-0.001, 36.0], -9}

                                           Consequent   Support  Confidence  \
12  {No code required - People aged under 16, peop...  0.265052         1.0

        Lift
12  3.772848
                                                Items  \
13  {No code required - People aged under 16, peop...

                                           Antecedent  \
13  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
13  {No code required - People aged under 16, peop...  0.265052         1.0

        Lift
13  3.772848
                                                Items  \
14  {No code required - People aged under 16, peop...

                                           Antecedent  \
14  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
14  {No code required - People aged under 16, peop...  0.265052         1.0

        Lift
14  3.772848
                                                Items  \
15  {No code required - People aged under 16, peop...

                                           Antecedent  \
15  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
15  {No code required - People aged under 16, peop...  0.265052         1.0

        Lift
15  3.772848
                                                Items  \
16  {No code required - People aged under 16, peop...

                                           Antecedent  \
16  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
16  {No code required - People aged under 16, peop...  0.265052         1.0

        Lift
16  3.772848
                                                Items  \
17  {No code required - People aged under 16, peop...

                                           Antecedent  \
17  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
17  {No code required - People aged under 16, peop...  0.265052         1.0

        Lift
17  3.772848
                                                Items  \
18  {No code required - People aged under 16, peop...

                                           Antecedent  \
18  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
18  {No code required - People aged under 16, peop...  0.258557    0.975497

        Lift
18  3.772848
                                                Items  \
19  {No code required - People aged under 16, peop...

                                           Antecedent  \
19  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
19  {No code required - People aged under 16, peop...  0.253116         1.0

        Lift
19  3.772848
                                                Items  \
20  {No code required - People aged under 16, peop...

                                           Antecedent  \
20  {Usual resident, No code required - People age...

                                           Consequent   Support  Confidence  \
20  {No code required - People aged under 16, peop...  0.253116         1.0

        Lift
20  3.772848
                                                Items  \
21  {No code required - People aged under 16, peop...

                                           Antecedent  \
21  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
21  {Usual resident, No code required - People age...  0.253116    0.954967

        Lift
21  3.772848
                                                Items  \
22  {No code required - People aged under 16, peop...

                                           Antecedent  \
22  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
22  {No code required - People aged under 16, peop...  0.258557    0.975497

        Lift
22  3.772848
                                                Items  \
23  {No code required - People aged under 16, peop...

                                           Antecedent  \
23  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
23  {No code required - People aged under 16, peop...  0.258557    0.975497

        Lift
23  3.772848
                                                Items  \
24  {No code required - People aged under 16, peop...

                                           Antecedent  \
24  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
24  {No code required - People aged under 16, peop...  0.258557    0.975497

        Lift
24  3.772848
                                                Items  \
25  {No code required - People aged under 16, peop...

                                           Antecedent  \
25  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
25  {No code required - People aged under 16, peop...  0.258557    0.975497

        Lift
25  3.772848
                                                Items  \
26  {No code required - People aged under 16, peop...

                                           Antecedent  \
26  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
26  {No code required - People aged under 16, peop...  0.258557    0.975497

        Lift
26  3.772848
                                                Items  \
27  {No code required - People aged under 16, peop...

                                           Antecedent  \
27  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
27  {No code required - People aged under 16, peop...  0.258557         1.0

        Lift
27  3.772848
                                                Items  \
28  {No code required - People aged under 16, peop...

                                           Antecedent  \
28  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
28  {No code required - People aged under 16, peop...  0.258557         1.0

        Lift
28  3.772848
                                                Items  \
29  {No code required - People aged under 16, peop...

                                           Antecedent  \
29  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
29  {-9, No code required - People aged under 16, ...  0.258557    0.975497

        Lift
29  3.772848
                                                Items  \
30  {No code required - People aged under 16, peop...

                                           Antecedent  \
30  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
30  {No code required - People aged under 16, peop...  0.258557         1.0

        Lift
30  3.772848
                                                Items  \
31  {No code required - People aged under 16, peop...

                                           Antecedent  \
31  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
31  {No code required - People aged under 16, peop...  0.258557         1.0

        Lift
31  3.772848
                                                Items  \
32  {No code required - People aged under 16, peop...

                                           Antecedent  \
32  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
32  {No code required - People aged under 16, peop...  0.258557    0.975497

        Lift
32  3.772848
                                                Items  \
33  {No code required - People aged under 16, peop...

                                           Antecedent  \
33  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
33  {No code required - People aged under 16, peop...  0.253116    0.954967

        Lift
33  3.772848
                                                Items  \
34  {No code required - People aged under 16, peop...

                                           Antecedent  \
34  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
34  {No code required - People aged under 16, peop...  0.253116    0.954967

        Lift
34  3.772848
                                                Items  \
35  {No code required - People aged under 16, peop...

                                        Antecedent  \
35  {Not resident in a communal establishment, -9}

                                           Consequent   Support  Confidence  \
35  {No code required - People aged under 16, peop...  0.258557         1.0

        Lift
35  3.772848
                                                Items  \
36  {No code required - People aged under 16, peop...

                                           Antecedent  \
36  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
36  {No code required - People aged under 16, peop...  0.253116    0.954967

        Lift
36  3.772848
                                                Items  \
37  {No code required - People aged under 16, peop...

                                           Antecedent  \
37  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
37  {No code required - People aged under 16, peop...  0.265052         1.0

        Lift
37  3.772848
                                                Items  \
38  {No code required - People aged under 16, peop...

                                           Antecedent  \
38  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
38  {(-0.001, 36.0], No code required - People age...  0.265052         1.0

        Lift
38  3.772848
                                                Items  \
39  {No code required - People aged under 16, peop...

                                           Antecedent  \
39  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
39  {No code required - People aged under 16, peop...  0.265052         1.0

        Lift
39  3.772848
                                                Items  \
40  {No code required - People aged under 16, peop...

                                           Antecedent  \
40  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
40  {(-0.001, 36.0], Not resident in a communal es...  0.258557    0.975497

        Lift
40  3.772848
                                                Items  \
41  {No code required - People aged under 16, peop...

                                           Antecedent  \
41  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
41  {No code required - People aged under 16, peop...  0.258557    0.975497

        Lift
41  3.772848
                                                Items  \
42  {No code required - People aged under 16, peop...

                                           Antecedent  \
42  {Not resident in a communal establishment, (-0...

                                           Consequent   Support  Confidence  \
42  {No code required - People aged under 16, peop...  0.258557         1.0

        Lift
42  3.772848
                                                Items  \
43  {No code required - People aged under 16, peop...

                                           Antecedent  \
43  {No code required - People aged under 16, peop...

                                        Consequent   Support  Confidence  \
43  {Not resident in a communal establishment, -9}  0.258557    0.975497

        Lift
43  3.772848
                                                Items  \
44  {No code required - People aged under 16, peop...

                                           Antecedent  \
44  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
44  {No code required - People aged under 16, peop...  0.258557         1.0

        Lift
44  3.772848
                                                Items  \
45  {No code required - People aged under 16, peop...

                                           Antecedent  \
45  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
45  {(-0.001, 36.0], No code required - People age...  0.258557         1.0

        Lift
45  3.772848
                                                Items  \
46  {No code required - People aged under 16, peop...

                                           Antecedent            Consequent  \
46  {No code required - People aged under 16, peop...  {(-0.001, 36.0], -9}

     Support  Confidence      Lift
46  0.258557         1.0  3.772848
                                                Items  \
47  {No code required - People aged under 16, peop...

                                           Antecedent  \
47  {No code required - People aged under 16, peop...

                                           Consequent   Support  Confidence  \
47  {No code required - People aged under 16, peop...  0.258557         1.0

        Lift
47  3.772848
                                                Items  \
48  {No code required - People aged under 16, peop...

                                           Antecedent Consequent   Support  \
48  {No code required - People aged under 16, peop...       {-9}  0.258557

    Confidence      Lift
48         1.0  3.772848
                                                Items Antecedent  \
49  {No code required - People aged under 16, peop...       {-9}

                                           Consequent   Support  Confidence  \
49  {No code required - People aged under 16, peop...  0.253116    0.954967

        Lift
49  3.772848
                                                Items  \
50  {No code required - People aged under 16, peop...

                                           Antecedent  \
50  {No code required - People aged under 16, peop...


                                                 Items  \
198  {No code required - People aged under 16, peop...

                                            Antecedent  \
198  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
198  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
198  3.772848
                                                 Items  \
199  {No code required - People aged under 16, peop...

                                            Antecedent  \
199  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
199  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
199  3.772848
                                                 Items  \
200  {No code required - People aged under 16, peop...

                                            Antecedent  \
200  {Usual resident, No code required - People age...

                                            Consequent   Support  Confidence  \
200  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
200  3.772848
                                                 Items  \
201  {No code required - People aged under 16, peop...

                                            Antecedent  \
201  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
201  {(-0.001, 36.0], No code required - People age...  0.253116         1.0

         Lift
201  3.772848
                                                 Items  \
202  {No code required - People aged under 16, peop...

                                            Antecedent            Consequent  \
202  {No code required - People aged under 16, peop...  {(-0.001, 36.0], -9}

      Support  Confidence      Lift
202  0.253116         1.0  3.772848
                                                 Items  \
203  {No code required - People aged under 16, peop...

                                            Antecedent  \
203  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
203  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
203  3.772848
                                                 Items  \
204  {No code required - People aged under 16, peop...

                                            Antecedent  \
204  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
204  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
204  3.772848
                                                 Items  \
205  {No code required - People aged under 16, peop...

                                            Antecedent Consequent   Support  \
205  {No code required - People aged under 16, peop...       {-9}  0.253116

     Confidence      Lift
205         1.0  3.772848
                                                 Items  \
206  {No code required - People aged under 16, peop...

                                            Antecedent  \
206  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
206  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
206  3.772848
                                                 Items  \
207  {No code required - People aged under 16, peop...

                                            Antecedent  \
207  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
207  {(-0.001, 36.0], No code required - People age...  0.265052         1.0

         Lift
207  3.772848
                                                 Items  \
208  {No code required - People aged under 16, peop...

                                            Antecedent  \
208  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
208  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
208  3.772848
                                                 Items  \
209  {No code required - People aged under 16, peop...

                                            Antecedent  \
209  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
209  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
209  3.772848
                                                 Items  \
210  {No code required - People aged under 16, peop...

                                            Antecedent  \
210  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
210  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
210  3.772848
                                                 Items  \
211  {Not resident in a communal establishment, No ...

                                         Antecedent  \
211  {Not resident in a communal establishment, -9}

                                            Consequent   Support  Confidence  \
211  {No code required - People aged under 16, peop...  0.258557         1.0

         Lift
211  3.772848
                                                 Items  \
212  {No code required - People aged under 16, peop...

                                            Antecedent Consequent   Support  \
212  {No code required - People aged under 16, peop...       {-9}  0.265052

     Confidence      Lift
212         1.0  3.772848
                                                 Items  \
213  {Not resident in a communal establishment, No ...

                                            Antecedent  \
213  {No code required - People aged under 16, peop...

                                         Consequent   Support  Confidence  \
213  {Not resident in a communal establishment, -9}  0.258557    0.975497

         Lift
213  3.772848
                                                 Items Antecedent  \
214  {Not resident in a communal establishment, No ...       {-9}

                                            Consequent   Support  Confidence  \
214  {No code required - People aged under 16, peop...  0.258557    0.975497

         Lift
214  3.772848
                                                 Items  \
215  {No code required - People aged under 16, peop...

                                            Antecedent Consequent   Support  \
215  {No code required - People aged under 16, peop...       {-9}  0.265052

     Confidence      Lift
215         1.0  3.772848
                                                 Items  \
216  {No code required - People aged under 16, peop...

                                            Antecedent  \
216  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
216  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
216  3.772848
                                                 Items  \
217  {No code required - People aged under 16, peop...

                                            Antecedent  \
217  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
217  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
217  3.772848
                                                 Items  \
218  {No code required - People aged under 16, peop...

                                            Antecedent  \
218  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
218  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
218  3.772848
                                                 Items  \
219  {No code required - People aged under 16, peop...

                                            Antecedent  \
219  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
219  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
219  3.772848
                                                 Items  \
220  {No code required - People aged under 16, peop...

                                            Antecedent  \
220  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
220  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
220  3.772848
                                                 Items Antecedent  \
221  {No code required - People aged under 16, peop...       {-9}

                                            Consequent   Support  Confidence  \
221  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
221  3.772848
                                                 Items  \
222  {No code required - People aged under 16, peop...

                                            Antecedent  \
222  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
222  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
222  3.772848
                                                 Items  \
223  {No code required - People aged under 16, peop...

                                            Antecedent  \
223  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
223  {(-0.001, 36.0], No code required - People age...  0.253116         1.0

         Lift
223  3.772848
                                                 Items  \
224  {No code required - People aged under 16, peop...

                                            Antecedent Consequent   Support  \
224  {No code required - People aged under 16, peop...       {-9}  0.265052

     Confidence      Lift
224         1.0  3.772848
                                                 Items  \
225  {No code required - People aged under 16, peop...

                                            Antecedent  \
225  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
225  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
225  3.772848
                                                 Items  \
226  {No code required - People aged under 16, peop...

                                            Antecedent  \
226  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
226  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
226  3.772848
                                                 Items Antecedent  \
227  {No code required - People aged under 16, peop...       {-9}

                                            Consequent   Support  Confidence  \
227  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
227  3.772848
                                                 Items  \
228  {No code required - People aged under 16, peop...

                                            Antecedent  \
228  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
228  {No code required - People aged under 16, peop...  0.258557         1.0

         Lift
228  3.772848
                                                 Items  \
229  {No code required - People aged under 16, peop...

                                            Antecedent  \
229  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
229  {No code required - People aged under 16, peop...  0.258557         1.0

         Lift
229  3.772848
                                                 Items  \
230  {No code required - People aged under 16, peop...

                                            Antecedent  \
230  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
230  {No code required - People aged under 16, peop...  0.258557         1.0

         Lift
230  3.772848
                                                 Items  \
231  {Not resident in a communal establishment, No ...

                                            Antecedent  \
231  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
231  {No code required - People aged under 16, peop...  0.258557         1.0

         Lift
231  3.772848
                                                 Items  \
232  {Not resident in a communal establishment, No ...

                                            Antecedent  \
232  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
232  {No code required - People aged under 16, peop...  0.258557         1.0

         Lift
232  3.772848
                                                 Items  \
233  {Not resident in a communal establishment, No ...

                                            Antecedent Consequent   Support  \
233  {No code required - People aged under 16, peop...       {-9}  0.258557

     Confidence      Lift
233         1.0  3.772848
                                                 Items Antecedent  \
234  {No code required - People aged under 16, peop...       {-9}

                                            Consequent   Support  Confidence  \
234  {No code required - People aged under 16, peop...  0.253116    0.954967

         Lift
234  3.772848
                                                 Items  \
235  {No code required - People aged under 16, peop...

                                            Antecedent  \
235  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
235  {No code required - People aged under 16, peop...  0.253116    0.954967

         Lift
235  3.772848
                                                 Items            Antecedent  \
236  {No code required - People aged under 16, peop...  {(-0.001, 36.0], -9}

                                            Consequent   Support  Confidence  \
236  {No code required - People aged under 16, peop...  0.253116    0.954967

         Lift
236  3.772848
                                                 Items  \
237  {No code required - People aged under 16, peop...

                                            Antecedent  \
237  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
237  {No code required - People aged under 16, peop...  0.253116    0.954967

         Lift
237  3.772848
                                                 Items  \
238  {No code required - People aged under 16, peop...

                                            Antecedent  \
238  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
238  {No code required - People aged under 16, peop...  0.253116    0.954967

         Lift
238  3.772848
                                                 Items            Antecedent  \
239  {No code required - People aged under 16, peop...  {Usual resident, -9}

                                            Consequent   Support  Confidence  \
239  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
239  3.772848
                                                 Items  \
240  {No code required - People aged under 16, peop...

                                            Antecedent  \
240  {No code required - People aged under 16, peop...

                               Consequent   Support  Confidence      Lift
240  {Usual resident, (-0.001, 36.0], -9}  0.253116    0.954967  3.772848
                                                 Items  \
241  {No code required - People aged under 16, peop...

                                            Antecedent  \
241  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
241  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
241  3.772848
                                                 Items  \
242  {No code required - People aged under 16, peop...

                                            Antecedent  \
242  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
242  {No code required - People aged under 16, peop...  0.253116    0.954967

         Lift
242  3.772848
                                                 Items  \
243  {No code required - People aged under 16, peop...

                               Antecedent  \
243  {Usual resident, (-0.001, 36.0], -9}

                                            Consequent   Support  Confidence  \
243  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
243  3.772848
                                                 Items  \
244  {No code required - People aged under 16, peop...

                                            Antecedent            Consequent  \
244  {No code required - People aged under 16, peop...  {Usual resident, -9}

      Support  Confidence      Lift
244  0.253116    0.954967  3.772848
                                                 Items  \
245  {No code required - People aged under 16, peop...

                                            Antecedent  \
245  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
245  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
245  3.772848
                                                 Items  \
246  {No code required - People aged under 16, peop...

                                            Antecedent  \
246  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
246  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
246  3.772848
                                                 Items  \
247  {Not resident in a communal establishment, No ...

                                            Antecedent            Consequent  \
247  {No code required - People aged under 16, peop...  {(-0.001, 36.0], -9}

      Support  Confidence      Lift
247  0.258557         1.0  3.772848
                                                 Items  \
248  {Not resident in a communal establishment, No ...

                                            Antecedent  \
248  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
248  {No code required - People aged under 16, peop...  0.258557         1.0

         Lift
248  3.772848
                                                 Items  \
249  {No code required - People aged under 16, peop...


                                                 Items  \
329  {No code required - People aged under 16, peop...

                                            Antecedent  \
329  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
329  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
329  3.772848
                                                 Items  \
330  {No code required - People aged under 16, peop...

                                            Antecedent  \
330  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
330  {Usual resident, No code required - People age...  0.253116    0.954967

         Lift
330  3.772848
                                                 Items  \
331  {No code required - People aged under 16, peop...

                                            Antecedent  \
331  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
331  {No code required - People aged under 16, peop...  0.253116    0.954967

         Lift
331  3.772848
                                                 Items  \
332  {No code required - People aged under 16, peop...

                                            Antecedent  \
332  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
332  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
332  3.772848
                                                 Items  \
333  {No code required - People aged under 16, peop...

                                            Antecedent  \
333  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
333  {(-0.001, 36.0], No code required - People age...  0.253116         1.0

         Lift
333  3.772848
                                                 Items  \
334  {No code required - People aged under 16, peop...

                                            Antecedent  \
334  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
334  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
334  3.772848
                                                 Items  \
335  {No code required - People aged under 16, peop...

                                            Antecedent  \
335  {No code required - People aged under 16, peop...

                               Consequent   Support  Confidence      Lift
335  {Usual resident, (-0.001, 36.0], -9}  0.253116    0.954967  3.772848
                                                 Items  \
336  {No code required - People aged under 16, peop...

                                            Antecedent  \
336  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
336  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
336  3.772848
                                                 Items  \
337  {No code required - People aged under 16, peop...

                                            Antecedent  \
337  {Usual resident, No code required - People age...

                                            Consequent   Support  Confidence  \
337  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
337  3.772848
                                                 Items  \
338  {No code required - People aged under 16, peop...

                                            Antecedent  \
338  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
338  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
338  3.772848
                                                 Items  \
339  {No code required - People aged under 16, peop...

                                            Antecedent  \
339  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
339  {-9, No code required - People aged under 16, ...  0.258557    0.975497

         Lift
339  3.772848
                                                 Items  \
340  {No code required - People aged under 16, peop...

                                            Antecedent  \
340  {Not resident in a communal establishment, (-0...

                                            Consequent   Support  Confidence  \
340  {No code required - People aged under 16, peop...  0.258557         1.0

         Lift
340  3.772848
                                                 Items  \
341  {No code required - People aged under 16, peop...

                                            Antecedent  \
341  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
341  {No code required - People aged under 16, peop...  0.253116    0.954967

         Lift
341  3.772848
                                                 Items  \
342  {No code required - People aged under 16, peop...

                                            Antecedent  \
342  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
342  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
342  3.772848
                                                 Items Antecedent  \
343  {No code required - People aged under 16, peop...       {-9}

                                            Consequent   Support  Confidence  \
343  {No code required - People aged under 16, peop...  0.258557    0.975497

         Lift
343  3.772848
                                                 Items Antecedent  \
344  {No code required - People aged under 16, peop...       {-9}

                                            Consequent   Support  Confidence  \
344  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
344  3.772848
                                                 Items  \
345  {No code required - People aged under 16, peop...

                                            Antecedent  \
345  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
345  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
345  3.772848
                                                 Items  \
346  {No code required - People aged under 16, peop...

                                            Antecedent  \
346  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
346  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
346  3.772848
                                                 Items  \
347  {No code required - People aged under 16, peop...

                                            Antecedent  \
347  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
347  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
347  3.772848
                                                 Items  \
348  {No code required - People aged under 16, peop...

                                            Antecedent  \
348  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
348  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
348  3.772848
                                                 Items  \
349  {No code required - People aged under 16, peop...

                                            Antecedent  \
349  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
349  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
349  3.772848
                                                 Items  \
350  {No code required - People aged under 16, peop...

                                            Antecedent  \
350  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
350  {No code required - People aged under 16, peop...  0.258557    0.975497

         Lift
350  3.772848
                                                 Items  \
351  {No code required - People aged under 16, peop...

                                            Antecedent  \
351  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
351  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
351  3.772848
                                                 Items  \
352  {No code required - People aged under 16, peop...

                                            Antecedent  \
352  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
352  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
352  3.772848
                                                 Items  \
353  {No code required - People aged under 16, peop...

                                            Antecedent  \
353  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
353  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
353  3.772848
                                                 Items  \
354  {No code required - People aged under 16, peop...

                                            Antecedent  \
354  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
354  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
354  3.772848
                                                 Items  \
355  {No code required - People aged under 16, peop...

                                            Antecedent Consequent   Support  \
355  {No code required - People aged under 16, peop...       {-9}  0.265052

     Confidence      Lift
355         1.0  3.772848
                                                 Items Antecedent  \
356  {No code required - People aged under 16, peop...       {-9}

                                            Consequent   Support  Confidence  \
356  {No code required - People aged under 16, peop...  0.258557    0.975497

         Lift
356  3.772848
                                                 Items  \
357  {No code required - People aged under 16, peop...

                                            Antecedent  \
357  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
357  {Not resident in a communal establishment, No ...  0.258557    0.975497

         Lift
357  3.772848
                                                 Items  \
358  {No code required - People aged under 16, peop...

                                            Antecedent  \
358  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
358  {No code required - People aged under 16, peop...  0.258557    0.975497

         Lift
358  3.772848
                                                 Items            Antecedent  \
359  {No code required - People aged under 16, peop...  {(-0.001, 36.0], -9}

                                            Consequent   Support  Confidence  \
359  {No code required - People aged under 16, peop...  0.258557    0.975497

         Lift
359  3.772848
                                                 Items  \
360  {No code required - People aged under 16, peop...

                                            Antecedent  \
360  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
360  {No code required - People aged under 16, peop...  0.258557    0.975497

         Lift
360  3.772848
                                                 Items  \
361  {No code required - People aged under 16, peop...

                                            Antecedent  \
361  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
361  {No code required - People aged under 16, peop...  0.258557    0.975497

         Lift
361  3.772848
                                                 Items  \
362  {No code required - People aged under 16, peop...

                                            Antecedent  \
362  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
362  {No code required - People aged under 16, peop...  0.258557    0.975497

         Lift
362  3.772848
                                                 Items  \
363  {No code required - People aged under 16, peop...

                                            Antecedent  \
363  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
363  {No code required - People aged under 16, peop...  0.258557    0.975497

         Lift
363  3.772848
                                                 Items  \
364  {No code required - People aged under 16, peop...

                                            Antecedent  \
364  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
364  {No code required - People aged under 16, peop...  0.258557    0.975497

         Lift
364  3.772848
                                                 Items  \
365  {No code required - People aged under 16, peop...

                                         Antecedent  \
365  {Not resident in a communal establishment, -9}

                                            Consequent   Support  Confidence  \
365  {No code required - People aged under 16, peop...  0.258557         1.0

         Lift
365  3.772848
                                                 Items  \
366  {No code required - People aged under 16, peop...

                                            Antecedent  \
366  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
366  {No code required - People aged under 16, peop...  0.258557    0.975497

         Lift
366  3.772848
                                                 Items  \
367  {No code required - People aged under 16, peop...

                                            Antecedent  \
367  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
367  {(-0.001, 36.0], -9, No code required - People...  0.258557    0.975497

         Lift
367  3.772848
                                                 Items  \
368  {No code required - People aged under 16, peop...

                                            Antecedent  \
368  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
368  {No code required - People aged under 16, peop...  0.258557    0.975497

         Lift
368  3.772848
                                                 Items  \
369  {No code required - People aged under 16, peop...

                                            Antecedent  \
369  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
369  {No code required - People aged under 16, peop...  0.258557         1.0

         Lift
369  3.772848
                                                 Items  \
370  {No code required - People aged under 16, peop...

                                            Antecedent  \
370  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
370  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
370  3.772848
                                                 Items  \
371  {No code required - People aged under 16, peop...

                                            Antecedent  \
371  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
371  {No code required - People aged under 16, peop...  0.258557         1.0

         Lift
371  3.772848
                                                 Items  \
372  {No code required - People aged under 16, peop...

                                            Antecedent  \
372  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
372  {No code required - People aged under 16, peop...  0.258557    0.975497

         Lift
372  3.772848
                                                 Items  \
373  {No code required - People aged under 16, peop...

                                            Antecedent  \
373  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
373  {No code required - People aged under 16, peop...  0.258557    0.975497

         Lift
373  3.772848
                                                 Items  \
374  {No code required - People aged under 16, peop...

                                            Antecedent  \
374  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
374  {(-0.001, 36.0], Usual resident, No code requi...  0.253116    0.954967

         Lift
374  3.772848
                                                 Items  \
375  {No code required - People aged under 16, peop...

                                            Antecedent  \
375  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
375  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
375  3.772848
                                                 Items  \
376  {No code required - People aged under 16, peop...

                                            Antecedent  \
376  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
376  {No code required - People aged under 16, peop...  0.258557    0.975497

         Lift
376  3.772848
                                                 Items  \
377  {No code required - People aged under 16, peop...

                                            Antecedent  \
377  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
377  {No code required - People aged under 16, peop...  0.258557         1.0

         Lift
377  3.772848
                                                 Items  \
378  {No code required - People aged under 16, peop...

                                            Antecedent  \

                                                 Items  \
502  {No code required - People aged under 16, peop...

                                            Antecedent            Consequent  \
502  {No code required - People aged under 16, peop...  {(-0.001, 36.0], -9}

      Support  Confidence      Lift
502  0.253116         1.0  3.772848
                                                 Items  \
503  {No code required - People aged under 16, peop...

                                            Antecedent  \
503  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
503  {No code required - People aged under 16, peop...  0.258557    0.975497

         Lift
503  3.772848
                                                 Items  \
504  {No code required - People aged under 16, peop...

                                            Antecedent  \
504  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
504  {No code required - People aged under 16, peop...  0.258557    0.975497

         Lift
504  3.772848
                                                 Items  \
505  {No code required - People aged under 16, peop...

                                            Antecedent  \
505  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
505  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
505  3.772848
                                                 Items  \
506  {No code required - People aged under 16, peop...

                                            Antecedent Consequent   Support  \
506  {No code required - People aged under 16, peop...       {-9}  0.253116

     Confidence      Lift
506         1.0  3.772848
                                                 Items  \
507  {No code required - People aged under 16, peop...

                                            Antecedent  \
507  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
507  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
507  3.772848
                                                 Items  \
508  {No code required - People aged under 16, peop...

                                            Antecedent  \
508  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
508  {No code required - People aged under 16, peop...  0.253116    0.954967

         Lift
508  3.772848
                                                 Items  \
509  {No code required - People aged under 16, peop...

                                            Antecedent  \
509  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
509  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
509  3.772848
                                                 Items  \
510  {No code required - People aged under 16, peop...

                                            Antecedent  \
510  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
510  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
510  3.772848
                                                 Items Antecedent  \
511  {No code required - People aged under 16, peop...       {-9}

                                            Consequent   Support  Confidence  \
511  {No code required - People aged under 16, peop...  0.258557    0.975497

         Lift
511  3.772848
                                                 Items  \
512  {No code required - People aged under 16, peop...

                                            Antecedent  \
512  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
512  {No code required - People aged under 16, peop...  0.258557    0.975497

         Lift
512  3.772848
                                                 Items  \
513  {No code required - People aged under 16, peop...

                                            Antecedent            Consequent  \
513  {No code required - People aged under 16, peop...  {Usual resident, -9}

      Support  Confidence      Lift
513  0.253116    0.954967  3.772848
                                                 Items  \
514  {No code required - People aged under 16, peop...

                                         Antecedent  \
514  {Not resident in a communal establishment, -9}

                                            Consequent   Support  Confidence  \
514  {No code required - People aged under 16, peop...  0.258557         1.0

         Lift
514  3.772848
                                                 Items  \
515  {No code required - People aged under 16, peop...

                                            Antecedent  \
515  {No code required - People aged under 16, peop...

                               Consequent   Support  Confidence      Lift
515  {Usual resident, (-0.001, 36.0], -9}  0.253116    0.954967  3.772848
                                                 Items  \
516  {No code required - People aged under 16, peop...

                                            Antecedent  \
516  {No code required - People aged under 16, peop...

                                         Consequent   Support  Confidence  \
516  {Not resident in a communal establishment, -9}  0.258557    0.975497

         Lift
516  3.772848
                                                 Items  \
517  {No code required - People aged under 16, peop...

                                            Antecedent  \
517  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
517  {No code required - People aged under 16, peop...  0.258557         1.0

         Lift
517  3.772848
                                                 Items  \
518  {No code required - People aged under 16, peop...

                                            Antecedent  \
518  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
518  {No code required - People aged under 16, peop...  0.258557         1.0

         Lift
518  3.772848
                                                 Items  \
519  {No code required - People aged under 16, peop...

                                            Antecedent Consequent   Support  \
519  {No code required - People aged under 16, peop...       {-9}  0.258557

     Confidence      Lift
519         1.0  3.772848
                                                 Items Antecedent  \
520  {No code required - People aged under 16, peop...       {-9}

                                            Consequent   Support  Confidence  \
520  {No code required - People aged under 16, peop...  0.253116    0.954967

         Lift
520  3.772848
                                                 Items  \
521  {No code required - People aged under 16, peop...

                                            Antecedent  \
521  {Usual resident, No code required - People age...

                                            Consequent   Support  Confidence  \
521  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
521  3.772848
                                                 Items            Antecedent  \
522  {No code required - People aged under 16, peop...  {Usual resident, -9}

                                            Consequent   Support  Confidence  \
522  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
522  3.772848
                                                 Items  \
523  {No code required - People aged under 16, peop...

                                            Antecedent  \
523  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
523  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
523  3.772848
                                                 Items  \
524  {No code required - People aged under 16, peop...

                                            Antecedent  \
524  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
524  {No code required - People aged under 16, peop...  0.258557    0.975497

         Lift
524  3.772848
                                                 Items  \
525  {No code required - People aged under 16, peop...

                                            Antecedent  \
525  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
525  {No code required - People aged under 16, peop...  0.258557         1.0

         Lift
525  3.772848
                                                 Items  \
526  {No code required - People aged under 16, peop...

                                            Antecedent  \
526  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
526  {No code required - People aged under 16, peop...  0.258557         1.0

         Lift
526  3.772848
                                                 Items  \
527  {No code required - People aged under 16, peop...

                                            Antecedent Consequent   Support  \
527  {No code required - People aged under 16, peop...       {-9}  0.258557

     Confidence      Lift
527         1.0  3.772848
                                                 Items Antecedent  \
528  {No code required - People aged under 16, peop...       {-9}

                                            Consequent   Support  Confidence  \
528  {No code required - People aged under 16, peop...  0.253116    0.954967

         Lift
528  3.772848
                                                 Items  \
529  {No code required - People aged under 16, peop...

                                            Antecedent  \
529  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
529  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
529  3.772848
                                                 Items  \
530  {No code required - People aged under 16, peop...

                                            Antecedent  \
530  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
530  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
530  3.772848
                                                 Items  \
531  {No code required - People aged under 16, peop...

                                            Antecedent  \
531  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
531  {No code required - People aged under 16, peop...  0.258557    0.975497

         Lift
531  3.772848
                                                 Items  \
532  {No code required - People aged under 16, peop...

                                            Antecedent  \
532  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
532  {No code required - People aged under 16, peop...  0.253116    0.954967

         Lift
532  3.772848
                                                 Items  \
533  {No code required - People aged under 16, peop...

                                            Antecedent  \
533  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
533  {Usual resident, No code required - People age...  0.253116    0.954967

         Lift
533  3.772848
                                                 Items            Antecedent  \
534  {No code required - People aged under 16, peop...  {Usual resident, -9}

                                            Consequent   Support  Confidence  \
534  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
534  3.772848
                                                 Items  \
535  {No code required - People aged under 16, peop...

                                            Antecedent  \
535  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
535  {(-0.001, 36.0], No code required - People age...  0.265052         1.0

         Lift
535  3.772848
                                                 Items  \
536  {No code required - People aged under 16, peop...

                                            Antecedent            Consequent  \
536  {No code required - People aged under 16, peop...  {Usual resident, -9}

      Support  Confidence      Lift
536  0.253116    0.954967  3.772848
                                                 Items Antecedent  \
537  {No code required - People aged under 16, peop...       {-9}

                                            Consequent   Support  Confidence  \
537  {No code required - People aged under 16, peop...  0.258557    0.975497

         Lift
537  3.772848
                                                 Items  \
538  {No code required - People aged under 16, peop...

                                            Antecedent Consequent   Support  \
538  {No code required - People aged under 16, peop...       {-9}  0.253116

     Confidence      Lift
538         1.0  3.772848
                                                 Items  \
539  {No code required - People aged under 16, peop...

                                            Antecedent  \
539  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
539  {No code required - People aged under 16, peop...  0.253116    0.954967

         Lift
539  3.772848
                                                 Items  \
540  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
540  {Married or in a registered same-sex civil par...

                                            Consequent   Support  Confidence  \
540  {Married/same-sex civil partnership couple fam...  0.292084    0.944918

         Lift
540  2.584348
                                                 Items  \
541  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
541  {Married or in a registered same-sex civil par...

                                            Consequent   Support  Confidence  \
541  {Married/same-sex civil partnership couple fam...  0.292084    0.944918

         Lift
541  2.584348
                                                 Items  \
542  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
542  {Married/same-sex civil partnership couple fam...

                                            Consequent   Support  Confidence  \
542  {Married or in a registered same-sex civil par...  0.292084    0.798848

         Lift
542  2.584348
                                                 Items  \
543  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
543  {Married or in a registered same-sex civil par...

                                            Consequent   Support  Confidence  \
543  {Married/same-sex civil partnership couple fam...  0.292084    0.944918

         Lift
543  2.584348
                                                 Items  \
544  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
544  {Married/same-sex civil partnership couple fam...

                                            Consequent   Support  Confidence  \
544  {Married or in a registered same-sex civil par...  0.292084    0.798848

         Lift
544  2.584348
                                                 Items  \
545  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
545  {Married/same-sex civil partnership couple fam...

                                            Consequent   Support  Confidence  \
545  {Married or in a registered same-sex civil par...  0.292084    0.798848

         Lift
545  2.584348
                                                 Items  \
546  {White, UK, Married/same-sex civil partnership...

                                            Antecedent  \
546  {Married/same-sex civil partnership couple fam...

                                            Consequent   Support  Confidence  \
546  {Married or in a registered same-sex civil par...  0.292084    0.798848

         Lift
546  2.571207
                                                 Items  \
547  {White, UK, Married/same-sex civil partnership...

                                            Antecedent  \
547  {Married/same-sex civil partnership couple fam...

                                            Consequent   Support  Confidence  \
547  {Married or in a registered same-sex civil par...  0.292084    0.798848

         Lift
547  2.571207
                                                 Items  \
548  {White, UK, Married/same-sex civil partnership...

                                            Antecedent  \
548  {Married/same-sex civil partnership couple fam...

                                            Consequent   Support  Confidence  \
548  {Married or in a registered same-sex civil par...  0.292084    0.798848

         Lift
548  2.571207
                                                 Items  \
549  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
549  {White, Not resident in a communal establishme...

                                            Consequent   Support  Confidence  \
549  {Married or in a registered same-sex civil par...  0.292084    0.798848

         Lift
549  2.571207
                                                 Items  \
550  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
550  {Married/same-sex civil partnership couple fam...

                                            Consequent   Support  Confidence  \
550  {Married or in a registered same-sex civil par...  0.292084    0.798848

         Lift
550  2.571207
                                                 Items  \
551  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
551  {Married/same-sex civil partnership couple fam...

                                            Consequent   Support  Confidence  \
551  {Married or in a registered same-sex civil par...  0.292084    0.798848

         Lift
551  2.571207
                                                 Items  \
552  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
552  {Married or in a registered same-sex civil par...

                                            Consequent   Support  Confidence  \
552  {White, Not resident in a communal establishme...  0.292084    0.940113

         Lift
552  2.571207

                                                 Items  \
696  {Married/same-sex civil partnership couple fam...

                                            Antecedent  \
696  {Married or in a registered same-sex civil par...

                                            Consequent   Support  Confidence  \
696  {Married/same-sex civil partnership couple fam...  0.299807    0.791841

         Lift
696  2.204846
                                                 Items  \
697  {UK, Not resident in a communal establishment,...

                                            Antecedent  \
697  {Married or in a registered same-sex civil par...

                                            Consequent   Support  Confidence  \
697  {UK, Not resident in a communal establishment,...  0.299807    0.791841

         Lift
697  2.204846
                                                 Items  \
698  {UK, Married/same-sex civil partnership couple...

                                            Antecedent  \
698  {Married/same-sex civil partnership couple fam...

                                            Consequent   Support  Confidence  \
698  {Married or in a registered same-sex civil par...  0.299807      0.8348

         Lift
698  2.204846
                                                 Items  \
699  {Married/same-sex civil partnership couple fam...

                                            Antecedent  \
699  {Married/same-sex civil partnership couple fam...

                                            Consequent   Support  Confidence  \
699  {Married or in a registered same-sex civil par...  0.299807      0.8348

         Lift
699  2.204846
                                                 Items  \
700  {UK, Not resident in a communal establishment,...

                                            Antecedent  \
700  {Married/same-sex civil partnership couple fam...

                                            Consequent   Support  Confidence  \
700  {Married or in a registered same-sex civil par...  0.299807      0.8348

         Lift
700  2.204846
                                                 Items  \
701  {UK, Not resident in a communal establishment,...

                                            Antecedent  \
701  {UK, Not resident in a communal establishment,...

                                            Consequent   Support  Confidence  \
701  {Married or in a registered same-sex civil par...  0.299807      0.8348

         Lift
701  2.204846
                                                 Items  \
702  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
702  {Married/same-sex civil partnership couple fam...

                                            Consequent   Support  Confidence  \
702  {Married or in a registered same-sex civil par...  0.293488    0.649068

         Lift
702  2.099797
                                                 Items  \
703  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
703  {Married or in a registered same-sex civil par...

                                            Consequent   Support  Confidence  \
703  {Married/same-sex civil partnership couple fam...  0.293488    0.949461

         Lift
703  2.099797
                                                 Items  \
704  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
704  {Married or in a registered same-sex civil par...

                                            Consequent   Support  Confidence  \
704  {Married/same-sex civil partnership couple fam...  0.293488    0.949461

         Lift
704  2.099797
                                                 Items  \
705  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
705  {Married/same-sex civil partnership couple fam...

                                            Consequent   Support  Confidence  \
705  {Married or in a registered same-sex civil par...  0.293488    0.649068

         Lift
705  2.099797
                                                 Items  \
706  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
706  {Married/same-sex civil partnership couple fam...

                                            Consequent   Support  Confidence  \
706  {Married or in a registered same-sex civil par...  0.293488    0.649068

         Lift
706  2.099797
                                                 Items  \
707  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
707  {Married or in a registered same-sex civil par...

                                            Consequent   Support  Confidence  \
707  {Married/same-sex civil partnership couple fam...  0.293488    0.949461

         Lift
707  2.099797
                                                 Items  \
708  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
708  {UK, Not resident in a communal establishment,...

                                            Consequent   Support  Confidence  \
708  {Married/same-sex civil partnership couple fam...  0.292084     0.94923

         Lift
708  2.099287
                                                 Items  \
709  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
709  {Married or in a registered same-sex civil par...

                                            Consequent   Support  Confidence  \
709  {Married/same-sex civil partnership couple fam...  0.292084     0.94923

         Lift
709  2.099287
                                                 Items  \
710  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
710  {Married or in a registered same-sex civil par...

                                            Consequent   Support  Confidence  \
710  {Married/same-sex civil partnership couple fam...  0.292084     0.94923

         Lift
710  2.099287
                                                 Items  \
711  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
711  {Married/same-sex civil partnership couple fam...

                                            Consequent   Support  Confidence  \
711  {Married or in a registered same-sex civil par...  0.292084    0.645963

         Lift
711  2.099287
                                                 Items  \
712  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
712  {Married/same-sex civil partnership couple fam...

                                            Consequent   Support  Confidence  \
712  {Married or in a registered same-sex civil par...  0.292084    0.645963

         Lift
712  2.099287
                                                 Items  \
713  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
713  {Married/same-sex civil partnership couple fam...

                                            Consequent   Support  Confidence  \
713  {UK, Not resident in a communal establishment,...  0.292084    0.645963

         Lift
713  2.099287
                                                 Items  \
714  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
714  {Married or in a registered same-sex civil par...

                                            Consequent   Support  Confidence  \
714  {Married/same-sex civil partnership couple fam...  0.293488    0.944633

        Lift
714  2.08912
                                                 Items  \
715  {White, UK, Married/same-sex civil partnership...

                                            Antecedent  \
715  {Married/same-sex civil partnership couple fam...

                                            Consequent   Support  Confidence  \
715  {Married or in a registered same-sex civil par...  0.293488    0.649068

        Lift
715  2.08912
                                                 Items  \
716  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
716  {Married or in a registered same-sex civil par...

                                            Consequent   Support  Confidence  \
716  {Married/same-sex civil partnership couple fam...  0.293488    0.944633

        Lift
716  2.08912
                                                 Items  \
717  {White, UK, Married/same-sex civil partnership...

                                            Antecedent  \
717  {Married or in a registered same-sex civil par...

                                            Consequent   Support  Confidence  \
717  {Married/same-sex civil partnership couple fam...  0.293488    0.944633

        Lift
717  2.08912
                                                 Items  \
718  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
718  {Married/same-sex civil partnership couple fam...

                                            Consequent   Support  Confidence  \
718  {Married or in a registered same-sex civil par...  0.293488    0.649068

        Lift
718  2.08912
                                                 Items  \
719  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
719  {Married or in a registered same-sex civil par...

                                            Consequent   Support  Confidence  \
719  {Married/same-sex civil partnership couple fam...  0.293488    0.944633

        Lift
719  2.08912
                                                 Items  \
720  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
720  {Married/same-sex civil partnership couple fam...

                                            Consequent   Support  Confidence  \
720  {Married or in a registered same-sex civil par...  0.293488    0.649068

        Lift
720  2.08912
                                                 Items  \
721  {Married/same-sex civil partnership couple fam...

                                            Antecedent  \
721  {Married/same-sex civil partnership couple fam...

                                            Consequent   Support  Confidence  \
721  {Married or in a registered same-sex civil par...  0.293488    0.649068

        Lift
721  2.08912
                                                 Items  \
722  {White, UK, Married/same-sex civil partnership...

                                            Antecedent  \
722  {Married or in a registered same-sex civil par...

                                            Consequent   Support  Confidence  \
722  {Married/same-sex civil partnership couple fam...  0.293488    0.944633

        Lift
722  2.08912
                                                 Items  \
723  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
723  {Married/same-sex civil partnership couple fam...

                                            Consequent   Support  Confidence  \
723  {Married or in a registered same-sex civil par...  0.293488    0.649068

        Lift
723  2.08912
                                                 Items  \
724  {Married/same-sex civil partnership couple fam...

                                            Antecedent  \
724  {Married or in a registered same-sex civil par...

                                            Consequent   Support  Confidence  \
724  {Married/same-sex civil partnership couple fam...  0.293488    0.944633

        Lift
724  2.08912
                                                 Items  \
725  {White, UK, Married/same-sex civil partnership...

                                            Antecedent  \
725  {Married/same-sex civil partnership couple fam...

                                            Consequent   Support  Confidence  \
725  {Married or in a registered same-sex civil par...  0.293488    0.649068

        Lift
725  2.08912
                                                 Items  \
726  {White, UK, Married/same-sex civil partnership...

                                            Antecedent  \
726  {Married or in a registered same-sex civil par...

                                            Consequent   Support  Confidence  \
726  {Married/same-sex civil partnership couple fam...  0.292084    0.944381

         Lift
726  2.088564
                                                 Items  \
727  {White, UK, Married/same-sex civil partnership...

                                            Antecedent  \
727  {Married/same-sex civil partnership couple fam...

                                            Consequent   Support  Confidence  \
727  {Married or in a registered same-sex civil par...  0.292084    0.645963

         Lift
727  2.088564
                                                 Items  \
728  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
728  {Married/same-sex civil partnership couple fam...

                                            Consequent   Support  Confidence  \
728  {Married or in a registered same-sex civil par...  0.292084    0.645963

         Lift
728  2.088564
                                                 Items  \
729  {White, UK, Married/same-sex civil partnership...

                                            Antecedent  \
729  {Married/same-sex civil partnership couple fam...

                                            Consequent   Support  Confidence  \
729  {Married or in a registered same-sex civil par...  0.292084    0.645963

         Lift
729  2.088564
                                                 Items  \
730  {White, UK, Married/same-sex civil partnership...

                                            Antecedent  \
730  {Married or in a registered same-sex civil par...

                                            Consequent   Support  Confidence  \
730  {Married/same-sex civil partnership couple fam...  0.292084    0.944381

         Lift
730  2.088564
                                                 Items  \
731  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
731  {Married or in a registered same-sex civil par...

                                            Consequent   Support  Confidence  \
731  {Married/same-sex civil partnership couple fam...  0.292084    0.944381

         Lift
731  2.088564
                                                 Items  \
732  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
732  {Married or in a registered same-sex civil par...

                                            Consequent   Support  Confidence  \
732  {Married/same-sex civil partnership couple fam...  0.292084    0.944381

         Lift
732  2.088564
                                                 Items  \
733  {White, UK, Married/same-sex civil partnership...

                                            Antecedent  \
733  {Married/same-sex civil partnership couple fam...

                                            Consequent   Support  Confidence  \
733  {Married or in a registered same-sex civil par...  0.292084    0.645963

         Lift
733  2.088564
                                                 Items  \
734  {White, UK, Married/same-sex civil partnership...

                                            Antecedent  \
734  {Married or in a registered same-sex civil par...

                                            Consequent   Support  Confidence  \
734  {Married/same-sex civil partnership couple fam...  0.292084    0.944381

         Lift
734  2.088564
                                                 Items  \
735  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
735  {Married/same-sex civil partnership couple fam...

                                            Consequent   Support  Confidence  \
735  {Married or in a registered same-sex civil par...  0.292084    0.645963

         Lift
735  2.088564
                                                 Items  \
736  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
736  {Married or in a registered same-sex civil par...

                                            Consequent   Support  Confidence  \
736  {Married/same-sex civil partnership couple fam...  0.292084    0.944381

         Lift
736  2.088564
                                                 Items  \
737  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
737  {Married/same-sex civil partnership couple fam...

                                            Consequent   Support  Confidence  \
737  {Married or in a registered same-sex civil par...  0.292084    0.645963

         Lift
737  2.088564
                                                 Items  \
738  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
738  {Married or in a registered same-sex civil par...

                                            Consequent   Support  Confidence  \
738  {Married/same-sex civil partnership couple fam...  0.292084    0.902386

         Lift
738  1.963672
                                                 Items  \
739  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
739  {Married or in a registered same-sex civil par...

                                            Consequent   Support  Confidence  \
739  {Married/same-sex civil partnership couple fam...  0.292084    0.902386

         Lift
739  1.963672
                                                 Items  \
740  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
740  {White, Not resident in a communal establishme...

                                            Consequent   Support  Confidence  \
740  {Married/same-sex civil partnership couple fam...  0.292084    0.902386

         Lift
740  1.963672
                                                 Items  \
741  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
741  {Married/same-sex civil partnership couple fam...

                                            Consequent   Support  Confidence  \
741  {White, Married or in a registered same-sex ci...  0.292084      0.6356

         Lift
741  1.963672
                                                 Items  \
742  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
742  {Married/same-sex civil partnership couple fam...

                                            Consequent   Support  Confidence  \
742  {White, Not resident in a communal establishme...  0.292084      0.6356

         Lift
742  1.963672
                                                 Items  \
743  {White, UK, Not resident in a communal establi...

                                            Antecedent  \
743  {Married/same-sex civil partnership couple fam...

                                            Consequent   Support  Confidence  \
743  {White, Married or in a registered same-sex ci...  0.292084      0.6356

         Lift
743  1.963672
                                                 Items  \
744  {White, UK, Not resident in a communal establi...


                                                 Items  \
858  {No code required - People aged under 16, peop...

                                            Antecedent  \
858  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
858  {No code required - People aged under 16, peop...  0.253116    0.472168

         Lift
858  1.865422
                                                 Items  \
859  {No code required - People aged under 16, peop...

                                            Antecedent  \
859  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
859  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
859  1.865422
                                                 Items  \
860  {No code required - People aged under 16, peop...

                                            Antecedent  \
860  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
860  {No code required - People aged under 16, peop...  0.258557         1.0

         Lift
860  1.865422
                                                 Items  \
861  {No code required - People aged under 16, peop...

                                            Antecedent  \
861  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
861  {Usual resident, No code required - People age...  0.253116    0.472168

         Lift
861  1.865422
                                                 Items  \
862  {No code required - People aged under 16, peop...

                                            Antecedent  \
862  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
862  {(-0.001, 36.0], Usual resident, No code requi...  0.253116    0.472168

         Lift
862  1.865422
                                                 Items  \
863  {No code required - People aged under 16, peop...

                                            Antecedent  \
863  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
863  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
863  1.865422
                                                 Items  \
864  {No code required - People aged under 16, peop...

                                            Antecedent  \
864  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
864  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
864  1.865422
                                                 Items  \
865  {No code required - People aged under 16, peop...

                                            Antecedent  \
865  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
865  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
865  1.865422
                                                 Items  \
866  {No code required - People aged under 16, peop...

                                            Antecedent  \
866  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
866  {No code required - People aged under 16, peop...  0.258557         1.0

         Lift
866  1.865422
                                                 Items  \
867  {No code required - People aged under 16, peop...

                                            Antecedent  \
867  {Not resident in a communal establishment, No ...

                                            Consequent   Support  Confidence  \
867  {No code required - People aged under 16, peop...  0.258557         1.0

         Lift
867  1.865422
                                                 Items  \
868  {No code required - People aged under 16, peop...

                                            Antecedent  \
868  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
868  {No code required - People aged under 16, peop...  0.258557    0.482318

         Lift
868  1.865422
                                                 Items  \
869  {No code required - People aged under 16, peop...

                                            Antecedent  \
869  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
869  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
869  1.865422
                                                 Items  \
870  {No code required - People aged under 16, peop...

                                            Antecedent  \
870  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
870  {No code required - People aged under 16, peop...  0.258557    0.482318

         Lift
870  1.865422
                                                 Items  \
871  {No code required - People aged under 16, peop...

                                            Antecedent  \
871  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
871  {-9, No code required - People aged under 16, ...  0.258557    0.482318

         Lift
871  1.865422
                                                 Items  \
872  {No code required - People aged under 16, peop...

                                            Antecedent  \
872  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
872  {(-0.001, 36.0], -9, No code required - People...  0.258557    0.482318

         Lift
872  1.865422
                                                 Items  \
873  {No code required - People aged under 16, peop...

                                            Antecedent  \
873  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
873  {No code required - People aged under 16, peop...  0.258557    0.482318

         Lift
873  1.865422
                                                 Items  \
874  {No code required - People aged under 16, peop...

                                            Antecedent  \
874  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
874  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
874  1.865422
                                                 Items  \
875  {No code required - People aged under 16, peop...

                                            Antecedent  \
875  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
875  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
875  1.865422
                                                 Items  \
876  {No code required - People aged under 16, peop...

                                            Antecedent  \
876  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
876  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
876  1.865422
                                                 Items  \
877  {No code required - People aged under 16, peop...

                                            Antecedent  \
877  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
877  {No code required - People aged under 16, peop...  0.258557         1.0

         Lift
877  1.865422
                                                 Items  \
878  {Not resident in a communal establishment, No ...

                                            Antecedent  \
878  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
878  {No code required - People aged under 16, peop...  0.258557    0.482318

         Lift
878  1.865422
                                                 Items Antecedent  \
879  {No code required - People aged under 16, peop...       {-9}

                                            Consequent   Support  Confidence  \
879  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
879  1.865422
                                                 Items  \
880  {No code required - People aged under 16, peop...

                                            Antecedent  \
880  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
880  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
880  1.865422
                                                 Items  \
881  {No code required - People aged under 16, peop...

                                            Antecedent  \
881  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
881  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
881  1.865422
                                                 Items  \
882  {No code required - People aged under 16, peop...

                                            Antecedent  \
882  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
882  {No code required - People aged under 16, peop...  0.253116    0.472168

         Lift
882  1.865422
                                                 Items  \
883  {No code required - People aged under 16, peop...

                               Antecedent  \
883  {Usual resident, (-0.001, 36.0], -9}

                                            Consequent   Support  Confidence  \
883  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
883  1.865422
                                                 Items Antecedent  \
884  {No code required - People aged under 16, peop...       {-9}

                                            Consequent   Support  Confidence  \
884  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
884  1.865422
                                                 Items  \
885  {No code required - People aged under 16, peop...

                                            Antecedent  \
885  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
885  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
885  1.865422
                                                 Items  \
886  {No code required - People aged under 16, peop...

                                            Antecedent  \
886  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
886  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
886  1.865422
                                                 Items            Antecedent  \
887  {No code required - People aged under 16, peop...  {Usual resident, -9}

                                            Consequent   Support  Confidence  \
887  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
887  1.865422
                                                 Items  \
888  {No code required - People aged under 16, peop...

                                            Antecedent            Consequent  \
888  {No code required - People aged under 16, peop...  {Usual resident, -9}

      Support  Confidence      Lift
888  0.253116    0.472168  1.865422
                                                 Items  \
889  {No code required - People aged under 16, peop...

                                            Antecedent  \
889  {No code required - People aged under 16, peop...

                               Consequent   Support  Confidence      Lift
889  {Usual resident, (-0.001, 36.0], -9}  0.253116    0.472168  1.865422
                                                 Items  \
890  {No code required - People aged under 16, peop...

                                            Antecedent  \
890  {Not resident in a communal establishment, (-0...

                                            Consequent   Support  Confidence  \
890  {No code required - People aged under 16, peop...  0.258557         1.0

         Lift
890  1.865422
                                                 Items            Antecedent  \
891  {No code required - People aged under 16, peop...  {(-0.001, 36.0], -9}

                                            Consequent   Support  Confidence  \
891  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
891  1.865422
                                                 Items  \
892  {No code required - People aged under 16, peop...

                                         Antecedent  \
892  {Not resident in a communal establishment, -9}

                                            Consequent   Support  Confidence  \
892  {No code required - People aged under 16, peop...  0.258557         1.0

         Lift
892  1.865422
                                                 Items  \
893  {No code required - People aged under 16, peop...

                                            Antecedent  \
893  {No code required - People aged under 16, peop...

                                         Consequent   Support  Confidence  \
893  {Not resident in a communal establishment, -9}  0.258557    0.482318

         Lift
893  1.865422
                                                 Items  \
894  {No code required - People aged under 16, peop...

                                            Antecedent  \
894  {Usual resident, No code required - People age...

                                            Consequent   Support  Confidence  \
894  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
894  1.865422
                                                 Items  \
895  {No code required - People aged under 16, peop...

                                            Antecedent  \
895  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
895  {No code required - People aged under 16, peop...  0.258557         1.0

         Lift
895  1.865422
                                                 Items  \
896  {No code required - People aged under 16, peop...

                                            Antecedent  \
896  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
896  {(-0.001, 36.0], Not resident in a communal es...  0.258557    0.482318

         Lift
896  1.865422
                                                 Items  \
897  {No code required - People aged under 16, peop...

                                            Antecedent  \
897  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
897  {No code required - People aged under 16, peop...  0.258557    0.482318

         Lift
897  1.865422
                                                 Items  \
898  {No code required - People aged under 16, peop...

                                            Antecedent  \
898  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
898  {No code required - People aged under 16, peop...  0.253116    0.472168

         Lift
898  1.865422
                                                 Items  \
899  {No code required - People aged under 16, peop...

                                            Antecedent  \
899  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
899  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
899  1.865422
                                                 Items  \
900  {No code required - People aged under 16, peop...

                                            Antecedent  \
900  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
900  {Usual resident, No code required - People age...  0.253116    0.472168

         Lift
900  1.865422
                                                 Items  \
901  {No code required - People aged under 16, peop...

                                            Antecedent  \
901  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
901  {No code required - People aged under 16, peop...  0.253116    0.472168

         Lift
901  1.865422
                                                 Items  \
902  {No code required - People aged under 16, peop...

                                            Antecedent  \
902  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
902  {No code required - People aged under 16, peop...  0.265052         1.0

         Lift
902  1.865422
                                                 Items  \
903  {No code required - People aged under 16, peop...

                                            Antecedent  \
903  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
903  {No code required - People aged under 16, peop...  0.258557    0.482318

         Lift
903  1.865422
                                                 Items  \
904  {No code required - People aged under 16, peop...

                                            Antecedent  \
904  {Usual resident, No code required - People age...

                                            Consequent   Support  Confidence  \
904  {No code required - People aged under 16, peop...  0.253116         1.0

         Lift
904  1.865422
                                                 Items  \
905  {No code required - People aged under 16, peop...

                                            Antecedent  \
905  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
905  {No code required - People aged under 16, peop...  0.258557    0.482318

         Lift
905  1.865422
                                                 Items  \
906  {No code required - People aged under 16, peop...

                                            Antecedent  \
906  {No code required - People aged under 16, peop...

                                            Consequent   Support  Confidence  \
906  {No code required - People aged under 16, peop...  0.258557         1.0

         Lift
906  1.865422
                                                 Items  \
907  {No code required - People aged under 16, peop...

                                            Antecedent  \

                                                  Items  \
1048  {White, UK, Not resident in a communal establi...

                                             Antecedent  \
1048  {Married or in a registered same-sex civil par...

                                             Consequent   Support  Confidence  \
1048  {Married/same-sex civil partnership couple fam...  0.293488    0.779851

         Lift
1048  1.83815
                                                  Items  \
1049  {White, UK, Not resident in a communal establi...

                                             Antecedent  \
1049  {Married or in a registered same-sex civil par...

                                             Consequent   Support  Confidence  \
1049  {Married/same-sex civil partnership couple fam...  0.293488    0.779851

         Lift
1049  1.83815
                                                  Items  \
1050  {White, UK, Married/same-sex civil partnership...

                                             Antecedent  \
1050  {Married/same-sex civil partnership couple fam...

                                             Consequent   Support  Confidence  \
1050  {Married or in a registered same-sex civil par...  0.292084    0.688457

          Lift
1050  1.837928
                                                  Items  \
1051  {White, UK, Married/same-sex civil partnership...

                                             Antecedent  \
1051  {Married/same-sex civil partnership couple fam...

                                             Consequent   Support  Confidence  \
1051  {Married or in a registered same-sex civil par...  0.292084    0.688457

          Lift
1051  1.837928
                                                  Items  \
1052  {White, UK, Married/same-sex civil partnership...

                                             Antecedent  \
1052  {Married or in a registered same-sex civil par...

                                             Consequent   Support  Confidence  \
1052  {Married/same-sex civil partnership couple fam...  0.292084    0.779756

          Lift
1052  1.837928
                                                  Items  \
1053  {White, UK, Not resident in a communal establi...

                                             Antecedent  \
1053  {Married or in a registered same-sex civil par...

                                             Consequent   Support  Confidence  \
1053  {Married/same-sex civil partnership couple fam...  0.292084    0.779756

          Lift
1053  1.837928
                                                  Items  \
1054  {White, UK, Married/same-sex civil partnership...

                                             Antecedent  \
1054  {Married or in a registered same-sex civil par...

                                             Consequent   Support  Confidence  \
1054  {Married/same-sex civil partnership couple fam...  0.292084    0.779756

          Lift
1054  1.837928
                                                  Items  \
1055  {White, UK, Not resident in a communal establi...

                                             Antecedent  \
1055  {Married/same-sex civil partnership couple fam...

                                             Consequent   Support  Confidence  \
1055  {Married or in a registered same-sex civil par...  0.292084    0.688457

          Lift
1055  1.837928
                                                  Items  \
1056  {White, UK, Not resident in a communal establi...

                                             Antecedent  \
1056  {White, UK, Not resident in a communal establi...

                                             Consequent   Support  Confidence  \
1056  {Married or in a registered same-sex civil par...  0.292084    0.688457

          Lift
1056  1.837928
                                                  Items  \
1057  {White, UK, Not resident in a communal establi...

                                             Antecedent  \
1057  {Married or in a registered same-sex civil par...

                                             Consequent   Support  Confidence  \
1057  {Married/same-sex civil partnership couple fam...  0.292084    0.779756

          Lift
1057  1.837928
                                                  Items  \
1058  {White, UK, Married/same-sex civil partnership...

                                             Antecedent  \
1058  {Married/same-sex civil partnership couple fam...

                                             Consequent   Support  Confidence  \
1058  {Married or in a registered same-sex civil par...  0.292084    0.688457

          Lift
1058  1.837928
                                                  Items  \
1059  {White, UK, Married/same-sex civil partnership...

                                             Antecedent  \
1059  {Married or in a registered same-sex civil par...

                                             Consequent   Support  Confidence  \
1059  {Married/same-sex civil partnership couple fam...  0.292084    0.779756

          Lift
1059  1.837928
                                                  Items  \
1060  {White, UK, Not resident in a communal establi...

                                             Antecedent  \
1060  {Married/same-sex civil partnership couple fam...

                                             Consequent   Support  Confidence  \
1060  {Married or in a registered same-sex civil par...  0.292084    0.688457

          Lift
1060  1.837928
                                                  Items  \
1061  {White, UK, Not resident in a communal establi...

                                             Antecedent  \
1061  {Married or in a registered same-sex civil par...

                                             Consequent   Support  Confidence  \
1061  {White, UK, Not resident in a communal establi...  0.292084    0.779756

          Lift
1061  1.837928
                                                  Items  \
1062  {Married/same-sex civil partnership couple fam...

                                             Antecedent  \
1062  {Married/same-sex civil partnership couple fam...

                                             Consequent   Support  Confidence  \
1062  {Married or in a registered same-sex civil par...  0.301211    0.569721

          Lift
1062  1.833729
                                                  Items  \
1063  {Married/same-sex civil partnership couple fam...

                                             Antecedent  \
1063  {Married/same-sex civil partnership couple fam...

                                             Consequent   Support  Confidence  \
1063  {Married or in a registered same-sex civil par...  0.301211    0.569721

          Lift
1063  1.833729
                                                  Items  \
1064  {Married/same-sex civil partnership couple fam...

                                             Antecedent  \
1064  {Married or in a registered same-sex civil par...

                                             Consequent   Support  Confidence  \
1064  {Married/same-sex civil partnership couple fam...  0.301211    0.969492

          Lift
1064  1.833729
                                                  Items  \
1065  {Married/same-sex civil partnership couple fam...

                                             Antecedent  \
1065  {Married/same-sex civil partnership couple fam...

                                             Consequent   Support  Confidence  \
1065  {Married or in a registered same-sex civil par...  0.301211    0.569721

          Lift
1065  1.833729
                                                  Items  \
1066  {Married/same-sex civil partnership couple fam...

                                             Antecedent  \
1066  {Married or in a registered same-sex civil par...

                                             Consequent   Support  Confidence  \
1066  {Married/same-sex civil partnership couple fam...  0.301211    0.969492

          Lift
1066  1.833729
                                                  Items  \
1067  {Married/same-sex civil partnership couple fam...

                                             Antecedent  \
1067  {Married or in a registered same-sex civil par...

                                             Consequent   Support  Confidence  \
1067  {Married/same-sex civil partnership couple fam...  0.301211    0.969492

          Lift
1067  1.833729
                                                  Items  \
1068  {Married/same-sex civil partnership couple fam...

                                             Antecedent  \
1068  {Married or in a registered same-sex civil par...

                                             Consequent   Support  Confidence  \
1068  {Married/same-sex civil partnership couple fam...  0.301211    0.969492

          Lift
1068  1.833729
                                                  Items  \
1069  {UK, Not resident in a communal establishment,...

                                             Antecedent  \
1069  {Married or in a registered same-sex civil par...

                                             Consequent   Support  Confidence  \
1069  {Married/same-sex civil partnership couple fam...  0.301211    0.969492

          Lift
1069  1.833729
                                                  Items  \
1070  {UK, Not resident in a communal establishment,...

                                             Antecedent  \
1070  {Married/same-sex civil partnership couple fam...

                                             Consequent   Support  Confidence  \
1070  {Married or in a registered same-sex civil par...  0.301211    0.569721

          Lift
1070  1.833729
                                                  Items  \
1071  {Married/same-sex civil partnership couple fam...

                                             Antecedent  \
1071  {Married/same-sex civil partnership couple fam...

                                             Consequent   Support  Confidence  \
1071  {Married or in a registered same-sex civil par...  0.301211    0.569721

          Lift
1071  1.833729
                                                  Items  \
1072  {UK, Not resident in a communal establishment,...

                                             Antecedent  \
1072  {Married or in a registered same-sex civil par...

                                             Consequent   Support  Confidence  \
1072  {Married/same-sex civil partnership couple fam...  0.301211    0.969492

          Lift
1072  1.833729
                                                  Items  \
1073  {UK, Not resident in a communal establishment,...

                                             Antecedent  \
1073  {Married/same-sex civil partnership couple fam...

                                             Consequent   Support  Confidence  \
1073  {Married or in a registered same-sex civil par...  0.301211    0.569721

          Lift
1073  1.833729
                                                  Items  \
1074  {UK, Married/same-sex civil partnership couple...

                                             Antecedent  \
1074  {Married/same-sex civil partnership couple fam...

                                             Consequent   Support  Confidence  \
1074  {Married or in a registered same-sex civil par...  0.299807    0.567065

          Lift
1074  1.833467
                                                  Items  \
1075  {Married/same-sex civil partnership couple fam...

                                             Antecedent  \
1075  {Married/same-sex civil partnership couple fam...

                                             Consequent   Support  Confidence  \
1075  {Married or in a registered same-sex civil par...  0.299807    0.567065

          Lift
1075  1.833467
                                                  Items  \
1076  {UK, Not resident in a communal establishment,...

                                             Antecedent  \
1076  {Married/same-sex civil partnership couple fam...

                                             Consequent   Support  Confidence  \
1076  {Married or in a registered same-sex civil par...  0.299807    0.567065

          Lift
1076  1.833467
                                                  Items  \
1077  {UK, Married/same-sex civil partnership couple...

                                             Antecedent  \
1077  {Married/same-sex civil partnership couple fam...

                                             Consequent   Support  Confidence  \
1077  {Married or in a registered same-sex civil par...  0.299807    0.567065

          Lift
1077  1.833467
                                                  Items  \
1078  {UK, Not resident in a communal establishment,...

                                             Antecedent  \
1078  {Married/same-sex civil partnership couple fam...

                                             Consequent   Support  Confidence  \
1078  {Married or in a registered same-sex civil par...  0.299807    0.567065

          Lift
1078  1.833467
                                                  Items  \
1079  {UK, Not resident in a communal establishment,...

                                             Antecedent  \
1079  {Married/same-sex civil partnership couple fam...

                                             Consequent   Support  Confidence  \
1079  {Married or in a registered same-sex civil par...  0.299807    0.567065

          Lift
1079  1.833467
                                                  Items  \
1080  {UK, Married/same-sex civil partnership couple...

                                             Antecedent  \
1080  {Married or in a registered same-sex civil par...

                                             Consequent   Support  Confidence  \
1080  {Married/same-sex civil partnership couple fam...  0.299807    0.969353

          Lift
1080  1.833467
                                                  Items  \
1081  {UK, Married/same-sex civil partnership couple...

                                             Antecedent  \
1081  {Married or in a registered same-sex civil par...

                                             Consequent   Support  Confidence  \
1081  {Married/same-sex civil partnership couple fam...  0.299807    0.969353

          Lift
1081  1.833467
                                                  Items  \
1082  {UK, Not resident in a communal establishment,...

                                             Antecedent  \
1082  {Married or in a registered same-sex civil par...

                                             Consequent   Support  Confidence  \
1082  {Married/same-sex civil partnership couple fam...  0.299807    0.969353

          Lift
1082  1.833467
                                                  Items  \
1083  {Married/same-sex civil partnership couple fam...

                                             Antecedent  \
1083  {Married or in a registered same-sex civil par...

                                             Consequent   Support  Confidence  \
1083  {Married/same-sex civil partnership couple fam...  0.299807    0.969353

          Lift
1083  1.833467
                                                  Items  \
1084  {UK, Not resident in a communal establishment,...

                                             Antecedent  \
1084  {Married or in a registered same-sex civil par...

                                             Consequent   Support  Confidence  \
1084  {Married/same-sex civil partnership couple fam...  0.299807    0.969353

          Lift
1084  1.833467
                                                  Items  \
1085  {UK, Not resident in a communal establishment,...

                                             Antecedent  \
1085  {Married or in a registered same-sex civil par...

                                             Consequent   Support  Confidence  \
1085  {Married/same-sex civil partnership couple fam...  0.299807    0.969353

          Lift
1085  1.833467
                                                  Items  \
1086  {White, Not resident in a communal establishme...

                                             Antecedent  \
1086  {Married/same-sex civil partnership couple fam...

                                             Consequent   Support  Confidence  \
1086  {White, Married or in a registered same-sex ci...  0.314903    0.595618

          Lift
1086  1.830223
                                                  Items  \
1087  {Married/same-sex civil partnership couple fam...

                                             Antecedent  \
1087  {Married/same-sex civil partnership couple fam...

                                             Consequent   Support  Confidence  \
1087  {Married or in a registered same-sex civil par...  0.314903    0.595618

          Lift
1087  1.830223
                                                  Items  \
1088  {White, Married/same-sex civil partnership cou...

                                             Antecedent  \
1088  {Married/same-sex civil partnership couple fam...

                                             Consequent   Support  Confidence  \
1088  {White, Married or in a registered same-sex ci...  0.314903    0.595618

          Lift
1088  1.830223
                                                  Items  \
1089  {White, Married/same-sex civil partnership cou...

                                             Antecedent  \
1089  {Married/same-sex civil partnership couple fam...

                                             Consequent   Support  Confidence  \
1089  {White, Married or in a registered same-sex ci...  0.314903    0.595618

          Lift
1089  1.830223
                                                  Items  \
1090  {White, Not resident in a communal establishme...

                                             Antecedent  \
1090  {Married/same-sex civil partnership couple fam...

                                             Consequent   Support  Confidence  \
1090  {White, Married or in a registered same-sex ci...  0.314903    0.595618

          Lift
1090  1.830223
                                                  Items  \
1091  {White, Not resident in a communal establishme...

                                             Antecedent  \
1091  {Married/same-sex civil partnership couple fam...

                                             Consequent   Support  Confidence  \
1091  {White, Married or in a registered same-sex ci...  0.314903    0.595618

          Lift
1091  1.830223
                                                  Items  \
1092  {White, Not resident in a communal establishme...

                                             Antecedent  \
1092  {Married or in a registered same-sex civil par...

                                             Consequent   Support  Confidence  \
1092  {Married/same-sex civil partnership couple fam...  0.314903    0.967638

          Lift
1092  1.830223
                                                  Items  \
1093  {Married/same-sex civil partnership couple fam...

                                             Antecedent  \
1093  {Married or in a registered same-sex civil par...

                                             Consequent   Support  Confidence  \
1093  {Married/same-sex civil partnership couple fam...  0.314903    0.967638

          Lift
1093  1.830223
                                                  Items  \
1094  {White, Married/same-sex civil partnership cou...

                                             Antecedent  \
1094  {Married or in a registered same-sex civil par...

                                             Consequent   Support  Confidence  \
1094  {Married/same-sex civil partnership couple fam...  0.314903    0.967638

          Lift
1094  1.830223
                                                  Items  \
1095  {White, Not resident in a communal establishme...


                                                  Items  \
1224  {UK, Not resident in a communal establishment,...

                                             Antecedent  \
1224  {Married/same-sex civil partnership couple fam...

                                             Consequent   Support  Confidence  \
1224  {Married or in a registered same-sex civil par...  0.301211    0.655462

          Lift
1224  1.732793
                                                  Items  \
1225  {Married/same-sex civil partnership couple fam...

                                             Antecedent  \
1225  {Married/same-sex civil partnership couple fam...

                                             Consequent   Support  Confidence  \
1225  {Married or in a registered same-sex civil par...  0.301211    0.655462

          Lift
1225  1.732793
                                                  Items  \
1226  {UK, Not resident in a communal establishment,...

                                             Antecedent  \
1226  {Married or in a registered same-sex civil par...

                                             Consequent   Support  Confidence  \
1226  {Married/same-sex civil partnership couple fam...  0.301211    0.796288

          Lift
1226  1.732793
                                                  Items  \
1227  {Married/same-sex civil partnership couple fam...

                                             Antecedent  \
1227  {Married or in a registered same-sex civil par...

                                             Consequent   Support  Confidence  \
1227  {Married/same-sex civil partnership couple fam...  0.301211    0.796288

          Lift
1227  1.732793
                                                  Items  \
1228  {UK, Not resident in a communal establishment,...

                                             Antecedent  \
1228  {Married/same-sex civil partnership couple fam...

                                             Consequent   Support  Confidence  \
1228  {Married or in a registered same-sex civil par...  0.301211    0.655462

          Lift
1228  1.731186
                                                  Items  \
1229  {Married/same-sex civil partnership couple fam...

                                             Antecedent  \
1229  {Married/same-sex civil partnership couple fam...

                                             Consequent   Support  Confidence  \
1229  {Married or in a registered same-sex civil par...  0.301211    0.655462

          Lift
1229  1.731186
                                                  Items  \
1230  {Married/same-sex civil partnership couple fam...

                                             Antecedent  \
1230  {Married/same-sex civil partnership couple fam...

                                             Consequent   Support  Confidence  \
1230  {Married or in a registered same-sex civil par...  0.301211    0.655462

          Lift
1230  1.731186
                                                  Items  \
1231  {Married/same-sex civil partnership couple fam...

                                             Antecedent  \
1231  {Married/same-sex civil partnership couple fam...

                                             Consequent   Support  Confidence  \
1231  {Married or in a registered same-sex civil par...  0.301211    0.655462

          Lift
1231  1.731186
                                                  Items  \
1232  {Married/same-sex civil partnership couple fam...

                                             Antecedent  \
1232  {Married or in a registered same-sex civil par...

                                             Consequent   Support  Confidence  \
1232  {Married/same-sex civil partnership couple fam...  0.301211    0.795549

          Lift
1232  1.731186
                                                  Items  \
1233  {UK, Not resident in a communal establishment,...

                                             Antecedent  \
1233  {Married or in a registered same-sex civil par...

                                             Consequent   Support  Confidence  \
1233  {Married/same-sex civil partnership couple fam...  0.301211    0.795549

          Lift
1233  1.731186
                                                  Items  \
1234  {Married/same-sex civil partnership couple fam...

                                             Antecedent  \
1234  {Married or in a registered same-sex civil par...

                                             Consequent   Support  Confidence  \
1234  {Married/same-sex civil partnership couple fam...  0.301211    0.795549

          Lift
1234  1.731186
                                                  Items  \
1235  {Married/same-sex civil partnership couple fam...

                                             Antecedent  \
1235  {Married or in a registered same-sex civil par...

                                             Consequent   Support  Confidence  \
1235  {Married/same-sex civil partnership couple fam...  0.301211    0.795549

          Lift
1235  1.731186
                                                  Items  \
1236  {UK, Single - never married or never registere...

                                             Antecedent  \
1236  {UK, No code required - People aged under 16, ...

                                             Consequent   Support  Confidence  \
1236  {(-0.001, 36.0], Usual resident, Not resident ...  0.258382    0.562047

          Lift
1236  1.550595
                                                  Items  \
1237  {UK, Single - never married or never registere...

                                             Antecedent  \
1237  {Single - never married or never registered a ...

                                             Consequent   Support  Confidence  \
1237  {UK, No code required - People aged under 16, ...  0.258382    0.712833

          Lift
1237  1.550595
                                                  Items  \
1238  {UK, Single - never married or never registere...

                                             Antecedent  \
1238  {UK, No code required - People aged under 16, ...

                                             Consequent   Support  Confidence  \
1238  {Single - never married or never registered a ...  0.258382      0.5759

          Lift
1238  1.547595
                                                  Items  \
1239  {UK, Single - never married or never registere...

                                             Antecedent  \
1239  {Single - never married or never registered a ...

                                             Consequent   Support  Confidence  \
1239  {UK, No code required - People aged under 16, ...  0.258382     0.69434

          Lift
1239  1.547595
                                                  Items  \
1240  {UK, Single - never married or never registere...

                                             Antecedent  \
1240  {UK, No code required - People aged under 16, ...

                                             Consequent   Support  Confidence  \
1240  {Single - never married or never registered a ...  0.264701    0.575792

          Lift
1240  1.547306
                                                  Items  \
1241  {UK, Single - never married or never registere...

                                             Antecedent  \
1241  {Single - never married or never registered a ...

                                             Consequent   Support  Confidence  \
1241  {UK, No code required - People aged under 16, ...  0.264701    0.711321

          Lift
1241  1.547306
                                                  Items  \
1242  {White, UK, Not resident in a communal establi...

                                             Antecedent  \
1242  {White, No code required - People aged under 1...

                           Consequent   Support  Confidence      Lift
1242  {UK, Christian, (-0.001, 36.0]}  0.259259    0.606571  1.531753
                                                  Items  \
1243  {White, UK, Not resident in a communal establi...

                           Antecedent  \
1243  {UK, Christian, (-0.001, 36.0]}

                                             Consequent   Support  Confidence  \
1243  {White, No code required - People aged under 1...  0.259259    0.654699

          Lift
1243  1.531753
                                                  Items  \
1244  {White, UK, Not resident in a communal establi...

                                           Antecedent  \
1244  {UK, Usual resident, Christian, (-0.001, 36.0]}

                                             Consequent   Support  Confidence  \
1244  {White, No code required - People aged under 1...  0.259259    0.654699

          Lift
1244  1.531124
                                                  Items  \
1245  {White, UK, Not resident in a communal establi...

                                             Antecedent  \
1245  {White, No code required - People aged under 1...

                           Consequent   Support  Confidence      Lift
1245  {UK, Christian, (-0.001, 36.0]}  0.259259    0.606322  1.531124
                                                  Items  \
1246  {White, UK, Not resident in a communal establi...

                                             Antecedent  \
1246  {White, No code required - People aged under 1...

                                           Consequent   Support  Confidence  \
1246  {UK, Usual resident, Christian, (-0.001, 36.0]}  0.259259    0.606322

          Lift
1246  1.531124
                                                  Items  \
1247  {White, UK, Not resident in a communal establi...

                           Antecedent  \
1247  {UK, Christian, (-0.001, 36.0]}

                                             Consequent   Support  Confidence  \
1247  {White, No code required - People aged under 1...  0.259259    0.654699

          Lift
1247  1.531124
                                                  Items  \
1248  {White, UK, No code required - People aged und...

                           Antecedent  \
1248  {UK, Christian, (-0.001, 36.0]}

                                             Consequent   Support  Confidence  \
1248  {White, No code required - People aged under 1...  0.265578    0.670656

          Lift
1248  1.526459
                                                  Items  \
1249  {White, UK, No code required - People aged und...

                                             Antecedent  \
1249  {White, No code required - People aged under 1...

                           Consequent   Support  Confidence      Lift
1249  {UK, Christian, (-0.001, 36.0]}  0.265578    0.604475  1.526459
                                                  Items  \
1250  {White, UK, No code required - People aged und...

                           Antecedent  \
1250  {UK, Christian, (-0.001, 36.0]}

                                             Consequent   Support  Confidence  \
1250  {White, No code required - People aged under 1...  0.265578    0.670656

          Lift
1250  1.524632
                                                  Items  \
1251  {White, UK, No code required - People aged und...

                                           Antecedent  \
1251  {UK, Usual resident, Christian, (-0.001, 36.0]}

                                             Consequent   Support  Confidence  \
1251  {White, No code required - People aged under 1...  0.265578    0.670656

          Lift
1251  1.524632
                                                  Items  \
1252  {White, UK, No code required - People aged und...

                                             Antecedent  \
1252  {White, No code required - People aged under 1...

                           Consequent   Support  Confidence      Lift
1252  {UK, Christian, (-0.001, 36.0]}  0.265578    0.603751  1.524632
                                                  Items  \
1253  {White, UK, No code required - People aged und...

                                             Antecedent  \
1253  {White, No code required - People aged under 1...

                                           Consequent   Support  Confidence  \
1253  {UK, Usual resident, Christian, (-0.001, 36.0]}  0.265578    0.603751

          Lift
1253  1.524632
                                                  Items  \
1254  {White, UK, Not resident in a communal establi...

                                             Antecedent  \
1254  {UK, Christian, (-0.001, 36.0], Not resident i...

                                             Consequent   Support  Confidence  \
1254  {White, No code required - People aged under 1...  0.259259    0.666516

          Lift
1254  1.517037
                                                  Items  \
1255  {White, UK, Not resident in a communal establi...

                                             Antecedent  \
1255  {White, No code required - People aged under 1...

                                             Consequent   Support  Confidence  \
1255  {UK, (-0.001, 36.0], Christian, Not resident i...  0.259259    0.590092

          Lift
1255  1.517037
                                                  Items  \
1256  {White, UK, Not resident in a communal establi...

                                             Antecedent  \
1256  {White, No code required - People aged under 1...

                                             Consequent   Support  Confidence  \
1256  {UK, (-0.001, 36.0], Christian, Not resident i...  0.259259    0.589385

          Lift
1256  1.515221
                                                  Items  \
1257  {White, UK, Not resident in a communal establi...

                                             Antecedent  \
1257  {UK, Not resident in a communal establishment,...

                                             Consequent   Support  Confidence  \
1257  {White, No code required - People aged under 1...  0.259259    0.666516

          Lift
1257  1.515221
                                                  Items  \
1258  {White, UK, Not resident in a communal establi...

                                             Antecedent  \
1258  {White, No code required - People aged under 1...

                                             Consequent   Support  Confidence  \
1258  {UK, Not resident in a communal establishment,...  0.259259    0.589385

          Lift
1258  1.515221
                                                  Items  \
1259  {White, UK, Not resident in a communal establi...

                                             Antecedent  \
1259  {UK, Christian, (-0.001, 36.0], Not resident i...

                                             Consequent   Support  Confidence  \
1259  {White, No code required - People aged under 1...  0.259259    0.666516

          Lift
1259  1.515221
                                                  Items  \
1260  {UK, Single - never married or never registere...

                                             Antecedent  \
1260  {UK, Single - never married or never registere...

                                             Consequent   Support  Confidence  \
1260  {No code required - People aged under 16, peop...  0.258382    0.769472

          Lift
1260  1.509013
                                                  Items  \
1261  {UK, Single - never married or never registere...

                                             Antecedent  \
1261  {No code required - People aged under 16, peop...

                                             Consequent   Support  Confidence  \
1261  {UK, Single - never married or never registere...  0.258382    0.506713

          Lift
1261  1.509013
                                                  Items  \
1262  {UK, Single - never married or never registere...

                                             Antecedent  \
1262  {UK, Single - never married or never registere...

                                             Consequent   Support  Confidence  \
1262  {No code required - People aged under 16, peop...  0.264701    0.788291

          Lift
1262  1.504991
                                                  Items  \
1263  {UK, Single - never married or never registere...

                                             Antecedent  \
1263  {No code required - People aged under 16, peop...

                                             Consequent   Support  Confidence  \
1263  {UK, Single - never married or never registere...  0.264701    0.505362

          Lift
1263  1.504991
                                                  Items  \
1264  {UK, Single - never married or never registere...

                                             Antecedent  \
1264  {UK, No code required - People aged under 16, ...

                                             Consequent   Support  Confidence  \
1264  {Single - never married or never registered a ...  0.258382    0.562047

          Lift
1264  1.503277
                                                  Items  \
1265  {UK, Single - never married or never registere...

                                             Antecedent  \
1265  {Single - never married or never registered a ...

                                             Consequent   Support  Confidence  \
1265  {UK, No code required - People aged under 16, ...  0.258382     0.69108

          Lift
1265  1.503277
                                                  Items  \
1266  {UK, Single - never married or never registere...

                                             Antecedent  \
1266  {UK, No code required - People aged under 16, ...

                                             Consequent   Support  Confidence  \
1266  {Single - never married or never registered a ...  0.258382    0.562047

          Lift
1266  1.503277
                                                  Items  \
1267  {UK, Single - never married or never registere...

                                             Antecedent  \
1267  {Single - never married or never registered a ...

                                             Consequent   Support  Confidence  \
1267  {UK, No code required - People aged under 16, ...  0.258382     0.69108

          Lift
1267  1.503277
                                                  Items  \
1268  {UK, Single - never married or never registere...

                                             Antecedent  \
1268  {UK, Single - never married or never registere...

                                             Consequent   Support  Confidence  \
1268  {No code required - People aged under 16, peop...  0.258382    0.785905

          Lift
1268  1.500436
                                                  Items  \
1269  {UK, Single - never married or never registere...

                                             Antecedent  \
1269  {No code required - People aged under 16, peop...

                                             Consequent   Support  Confidence  \
1269  {UK, Single - never married or never registere...  0.258382    0.493298

          Lift
1269  1.500436

In [36]:
print(above_1.loc[[9]])

                                               Items  \
9  {No code required - People aged under 16, peop...

                                          Antecedent  \
9  {No code required - People aged under 16, peop...

                                          Consequent   Support  Confidence  \
9  {No code required - People aged under 16, peop...  0.265052         1.0

       Lift
9  3.772848

In [38]:
data_list = []
for row in range(0, 5697):
    data_list.append([str(census1.values[row,column]) for column in range(0, 19)])
    
rules = apriori(data_list, min_support=0.25, min_confidence=0.25, min_length=2)
results = list(rules)